admin_payment_preferences:
  path: /preferences
  methods: [ GET ]
  defaults:
    _legacy_controller: AdminPaymentPreferences
    _legacy_link: AdminPaymentPreferences
    _controller: PrestaShopBundle\Controller\Admin\Improve\Payment\PaymentPreferencesController::indexAction

admin_payment_carrier_restrictions_save:
  path: /carrier-restrictions
  methods: [ POST ]
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\Improve\Payment\PaymentPreferencesController::processPaymentCarrierRestrictionsFormAction'
    _legacy_controller: AdminPaymentPreferences
    _legacy_link: AdminPaymentPreferences:update

admin_payment_country_restrictions_save:
  path: /country-restrictions
  methods: [ POST ]
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\Improve\Payment\PaymentPreferencesController::processPaymentCountryRestrictionsFormAction'
    _legacy_controller: AdminPaymentPreferences
    _legacy_link: AdminPaymentPreferences:update

admin_payment_currency_restrictions_save:
  path: /currency-restrictions
  methods: [ POST ]
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\Improve\Payment\PaymentPreferencesController::processPaymentCurrencyRestrictionsFormAction'
    _legacy_controller: AdminPaymentPreferences
    _legacy_link: AdminPaymentPreferences:update

admin_payment_group_restrictions_save:
  path: /group-restrictions
  methods: [ POST ]
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\Improve\Payment\PaymentPreferencesController::processPaymentGroupRestrictionsFormAction'
    _legacy_controller: AdminPaymentPreferences
    _legacy_link: AdminPaymentPreferences:update
