_combinations:
    resource: 'combination.yml'

_images:
    resource: 'image.yml'

admin_products_v2_index:
  path: /
  methods: [GET]
  defaults:
    _controller: PrestaShopBundle:Admin/Sell/Catalog/Product/Product:index
    _legacy_controller: AdminProducts

admin_products_search:
    path: /
    methods: [POST]
    defaults:
        _controller: PrestaShopBundle:Admin\Common:searchGrid
        gridDefinitionFactoryServiceId: prestashop.core.grid.definition.factory.product
        redirectRoute: admin_products_v2_index
        _legacy_controller: AdminProducts

admin_products_v2_create:
  path: /create
  methods: [GET, POST]
  defaults:
    _controller: PrestaShopBundle:Admin/Sell/Catalog/Product/Product:create
    _legacy_controller: AdminProducts
    _legacy_link:
      - AdminProducts:addproduct
      - AdminProducts:add

admin_products_v2_edit:
  path: /{productId}/edit
  methods: [GET, POST, PATCH]
  defaults:
    _controller: PrestaShopBundle:Admin/Sell/Catalog/Product/Product:edit
    _legacy_controller: AdminProducts
    _legacy_link:
      - AdminProducts:updateproduct
      - AdminProducts:update
    _legacy_parameters:
      id_product: productId
  requirements:
    productId: \d+

admin_products_v2_delete:
    path: /{productId}/delete
    methods: [POST, DELETE]
    defaults:
        _controller: PrestaShopBundle:Admin/Sell/Catalog/Product/Product:delete
        _legacy_controller: AdminProducts
        _legacy_link:
            - AdminProducts:delete
        _legacy_parameters:
            id_product: productId
    requirements:
        productId: \d+
