services:
    _defaults:
        public: true

    prestashop.core.form.command_builder.product_commands_builder:
        class: PrestaShop\PrestaShop\Core\Form\IdentifiableObject\CommandBuilder\Product\ProductCommandsBuilder
        arguments:
            -
                - '@prestashop.core.form.command_builder.product.basic_information'
                - '@prestashop.core.form.command_builder.product.prices'
                - '@prestashop.core.form.command_builder.product.seo'
                - '@prestashop.core.form.command_builder.product.shipping'
                - '@prestashop.core.form.command_builder.product.options_command_builder'
                - '@prestashop.core.form.command_builder.product.product_suppliers_command_builder'
                - '@prestashop.core.form.command_builder.product.stock_command_builder'
                - '@prestashop.core.form.command_builder.product.feature_values_command_builder'
                - '@prestashop.core.form.command_builder.product.customization_fields_command_builder'
                # VERY IMPORTANT this builder must be the last one, it will avoid conflicts with previous commands
                # that may not be compatible with the updated type, ideally we would need the ability to define
                # priorities for each builder
                - '@prestashop.core.form.command_builder.product.type'

    prestashop.core.form.command_builder.product.type:
        class: PrestaShop\PrestaShop\Core\Form\IdentifiableObject\CommandBuilder\Product\TypeCommandBuilder

    prestashop.core.form.command_builder.product.basic_information:
        class: PrestaShop\PrestaShop\Core\Form\IdentifiableObject\CommandBuilder\Product\BasicInformationCommandBuilder

    prestashop.core.form.command_builder.product.prices:
        class: PrestaShop\PrestaShop\Core\Form\IdentifiableObject\CommandBuilder\Product\PricesCommandBuilder

    prestashop.core.form.command_builder.product.seo:
        class: PrestaShop\PrestaShop\Core\Form\IdentifiableObject\CommandBuilder\Product\SEOCommandBuilder

    prestashop.core.form.command_builder.product.shipping:
        class: PrestaShop\PrestaShop\Core\Form\IdentifiableObject\CommandBuilder\Product\ShippingCommandBuilder

    prestashop.core.form.command_builder.product.options_command_builder:
        class: PrestaShop\PrestaShop\Core\Form\IdentifiableObject\CommandBuilder\Product\OptionsCommandBuilder

    prestashop.core.form.command_builder.product.stock_command_builder:
        class: PrestaShop\PrestaShop\Core\Form\IdentifiableObject\CommandBuilder\Product\StockCommandBuilder

    prestashop.core.form.command_builder.product.product_suppliers_command_builder:
        class: PrestaShop\PrestaShop\Core\Form\IdentifiableObject\CommandBuilder\Product\ProductSuppliersCommandBuilder

    prestashop.core.form.command_builder.product.feature_values_command_builder:
        class: PrestaShop\PrestaShop\Core\Form\IdentifiableObject\CommandBuilder\Product\FeatureValuesCommandBuilder

    prestashop.core.form.command_builder.product.customization_fields_command_builder:
        class: PrestaShop\PrestaShop\Core\Form\IdentifiableObject\CommandBuilder\Product\CustomizationFieldsCommandBuilder

    # Combination builders
    prestashop.core.form.command_builder.combination.combination_commands_builder:
        class: PrestaShop\PrestaShop\Core\Form\IdentifiableObject\CommandBuilder\Product\Combination\CombinationCommandsBuilder
        arguments:
            - !tagged core.combination_command_builder

    prestashop.core.form.command_builder.product.combination.stock_command_builder:
        class: PrestaShop\PrestaShop\Core\Form\IdentifiableObject\CommandBuilder\Product\Combination\CombinationStockCommandsBuilder
        tags: ['core.combination_command_builder']
