services:
    _defaults:
        public: true

    prestashop.core.form.command_builder.product_commands_builder:
        class: PrestaShop\PrestaShop\Core\Form\IdentifiableObject\CommandBuilder\Product\ProductCommandsBuilder
        arguments:
            -
                - '@prestashop.core.form.command_builder.product.basic_information'
                - '@prestashop.core.form.command_builder.product.prices'
                - '@prestashop.core.form.command_builder.product.seo'
                - '@prestashop.core.form.command_builder.product.shipping'
                - '@prestashop.core.form.command_builder.product.options_command_builder'
                - '@prestashop.core.form.command_builder.product.product_suppliers_command_builder'
                - '@prestashop.core.form.command_builder.product.stock_command_builder'
                - '@prestashop.core.form.command_builder.product.feature_values_command_builder'
                - '@prestashop.core.form.command_builder.product.customization_fields_command_builder'

    prestashop.core.form.command_builder.product.basic_information:
        class: PrestaShop\PrestaShop\Core\Form\IdentifiableObject\CommandBuilder\Product\BasicInformationCommandBuilder

    prestashop.core.form.command_builder.product.prices:
        class: PrestaShop\PrestaShop\Core\Form\IdentifiableObject\CommandBuilder\Product\PricesCommandBuilder

    prestashop.core.form.command_builder.product.seo:
        class: PrestaShop\PrestaShop\Core\Form\IdentifiableObject\CommandBuilder\Product\SEOCommandBuilder

    prestashop.core.form.command_builder.product.shipping:
        class: PrestaShop\PrestaShop\Core\Form\IdentifiableObject\CommandBuilder\Product\ShippingCommandBuilder

    prestashop.core.form.command_builder.product.options_command_builder:
        class: PrestaShop\PrestaShop\Core\Form\IdentifiableObject\CommandBuilder\Product\OptionsCommandBuilder

    prestashop.core.form.command_builder.product.stock_command_builder:
        class: PrestaShop\PrestaShop\Core\Form\IdentifiableObject\CommandBuilder\Product\StockCommandBuilder

    prestashop.core.form.command_builder.product.product_suppliers_command_builder:
        class: PrestaShop\PrestaShop\Core\Form\IdentifiableObject\CommandBuilder\Product\ProductSuppliersCommandBuilder

    prestashop.core.form.command_builder.product.feature_values_command_builder:
        class: PrestaShop\PrestaShop\Core\Form\IdentifiableObject\CommandBuilder\Product\FeatureValuesCommandBuilder

    prestashop.core.form.command_builder.product.customization_fields_command_builder:
        class: PrestaShop\PrestaShop\Core\Form\IdentifiableObject\CommandBuilder\Product\CustomizationFieldsCommandBuilder
