services:
  _defaults:
    public: true

  prestashop.core.form.identifiable_object.handler.form_handler_factory:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandlerFactory'
    arguments:
      - '@prestashop.core.hook.dispatcher'
      - '@translator'
      - '@=service("prestashop.adapter.legacy.configuration").get("_PS_MODE_DEMO_")'

  prestashop.core.form.identifiable_object.sql_request_form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
    factory: 'prestashop.core.form.identifiable_object.handler.form_handler_factory:create'
    arguments:
      - '@prestashop.core.form.identifiable_object.sql_request_form_data_handler'

  prestashop.core.form.identifiable_object.handler.customer_form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
    factory: 'prestashop.core.form.identifiable_object.handler.form_handler_factory:create'
    arguments:
      - '@prestashop.core.form.identifiable_object.data_handler.customer_form_data_handler'

  prestashop.core.form.identifiable_object.handler.language_form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
    factory: 'prestashop.core.form.identifiable_object.handler.form_handler_factory:create'
    arguments:
      - '@prestashop.core.form.identifiable_object.data_handler.language_form_data_handler'

  prestashop.core.form.identifiable_object.currency_form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
    factory: 'prestashop.core.form.identifiable_object.handler.form_handler_factory:create'
    arguments:
      - '@prestashop.core.form.identifiable_object.currency_form_data_handler'

  prestashop.core.form.identifiable_object.handler.webservice_key_form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
    factory: 'prestashop.core.form.identifiable_object.handler.form_handler_factory:create'
    arguments:
      - '@prestashop.core.form.identifiable_object.data_handler.webservice_key_form_data_handler'


  prestashop.core.form.identifiable_object.meta_form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
    factory: 'prestashop.core.form.identifiable_object.handler.form_handler_factory:create'
    arguments:
      - '@prestashop.core.form.identifiable_object.meta_form_data_handler'

  prestashop.core.form.identifiable_object.handler.category_form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
    factory: 'prestashop.core.form.identifiable_object.handler.form_handler_factory:create'
    arguments:
      - '@prestashop.core.form.identifiable_object.data_handler.category_form_data_handler'

  prestashop.core.form.identifiable_object.handler.root_category_form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
    factory: 'prestashop.core.form.identifiable_object.handler.form_handler_factory:create'
    arguments:
      - '@prestashop.core.form.identifiable_object.data_handler.root_category_form_data_handler'

  prestashop.core.form.identifiable_object.handler.contact_form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
    factory: 'prestashop.core.form.identifiable_object.handler.form_handler_factory:create'
    arguments:
      - '@prestashop.core.form.identifiable_object.data_handler.contact_form_data_handler'

  prestashop.core.form.identifiable_object.handler.cms_page_category_form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
    factory: 'prestashop.core.form.identifiable_object.handler.form_handler_factory:create'
    arguments:
      - '@prestashop.core.form.identifiable_object.data_handler.cms_page_category_form_data_handler'

  prestashop.core.form.identifiable_object.handler.tax_form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
    factory: 'prestashop.core.form.identifiable_object.handler.form_handler_factory:create'
    arguments:
      - '@prestashop.core.form.identifiable_object.data_handler.tax_form_data_handler'

  prestashop.core.form.identifiable_object.handler.manufacturer_form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
    factory: 'prestashop.core.form.identifiable_object.handler.form_handler_factory:create'
    arguments:
      - '@prestashop.core.form.identifiable_object.data_handler.manufacturer_form_data_handler'

  prestashop.core.form.identifiable_object.handler.employee_form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
    factory: 'prestashop.core.form.identifiable_object.handler.form_handler_factory:create'
    arguments:
      - '@prestashop.core.form.identifiable_object.data_handler.employee_form_data_handler'

  prestashop.core.form.identifiable_object.handler.profile_form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
    factory: 'prestashop.core.form.identifiable_object.handler.form_handler_factory:create'
    arguments:
      - '@prestashop.core.form.identifiable_object.data_handler.profile_form_data_handler'

  prestashop.core.form.identifiable_object.handler.cms_page_form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
    factory: 'prestashop.core.form.identifiable_object.handler.form_handler_factory:create'
    arguments:
      - '@prestashop.core.form.identifiable_object.data_handler.cms_page_form_data_handler'

  prestashop.core.form.identifiable_object.handler.manufacturer_address_form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
    factory: 'prestashop.core.form.identifiable_object.handler.form_handler_factory:create'
    arguments:
      - '@prestashop.core.form.identifiable_object.data_handler.manufacturer_address_form_data_handler'
