services:
  _defaults:
    public: true
    bind:
      $queryBus: '@prestashop.core.query_bus'

  prestashop.core.form.identifiable_object.data_provider.sql_request_form_data_provider:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\SqlRequestFormDataProvider'
    arguments:
      - '@prestashop.core.query_bus'

  prestashop.core.form.identifiable_object.data_provider.customer_form_data_provider:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\CustomerFormDataProvider'
    arguments:
      - '@prestashop.core.query_bus'
      - '@prestashop.adapter.legacy.configuration'
      - '@prestashop.adapter.group.provider.default_groups_provider'
      - '@=service("prestashop.core.b2b.b2b_feature").isActive()'

  prestashop.core.form.identifiable_object.data_provider.language_form_data_provider:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\LanguageFormDataProvider'
    arguments:
      - '@prestashop.core.command_bus'
      - '@=service("prestashop.adapter.multistore_feature").isActive()'
      - '@=service("prestashop.adapter.shop.context").getShops(true, true)'

  prestashop.core.form.identifiable_object.data_provider.currency_form_data_provider:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\CurrencyFormDataProvider'
    arguments:
      - '@prestashop.core.query_bus'
      - '@=service("prestashop.adapter.shop.context").getContextListShopID()'

  prestashop.core.form.identifiable_object.data_provider.webservice_key_form_data_provider:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\WebserviceKeyFormDataProvider'
    arguments:
      - '@prestashop.core.query_bus'
      - '@=service("prestashop.adapter.shop.context").getShops(true, true)'

  prestashop.core.form.identifiable_object.data_provider.meta_form_data_provider:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\MetaFormDataProvider'
    arguments:
      - '@prestashop.core.query_bus'

  prestashop.core.form.identifiable_object.data_provider.category_form_data_provider:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\CategoryFormDataProvider'
    arguments:
      - '@prestashop.core.query_bus'
      - '@=service("prestashop.adapter.shop.context").getContextListShopID()'
      - '@=service("prestashop.adapter.legacy.context").getContext().shop.getCategory()'
      - '@prestashop.adapter.group.group_data_provider'
      - '@prestashop.adapter.shop.url.category_provider'
      - '@router.default'

  prestashop.core.form.identifiable_object.data_provider.contact_form_data_provider:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\ContactFormDataProvider'
    arguments:
      - '@prestashop.core.query_bus'
      - '@PrestaShopBundle\Form\DataTransformer\StringArrayToIntegerArrayDataTransformer'
      - '@=service("prestashop.adapter.shop.context").getContextListShopID()'

  prestashop.core.form.identifiable_object.data_provider.store_form_data_provider:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\StoreFormDataProvider'
    arguments:
      - '@prestashop.core.query_bus'
      - '@PrestaShopBundle\Form\DataTransformer\StringArrayToIntegerArrayDataTransformer'
      - '@=service("prestashop.adapter.shop.context").getContextListShopID()'

  prestashop.core.form.identifiable_object.data_provider.cms_page_category_form_data_provider:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\CmsPageCategoryFormDataProvider'
    arguments:
      - '@prestashop.core.query_bus'
      - '@=service("prestashop.adapter.shop.context").getContextListShopID()'

  prestashop.core.form.identifiable_object.data_provider.tax_form_data_provider:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\TaxFormDataProvider'
    arguments:
      - '@prestashop.core.query_bus'

  prestashop.core.form.identifiable_object.data_provider.manufacturer_address_form_data_provider:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\ManufacturerAddressFormDataProvider'
    arguments:
      - '@prestashop.core.query_bus'
      - '@=service("prestashop.adapter.legacy.context").getContext().country.id'

  prestashop.core.form.identifiable_object.data_provider.manufacturer_form_data_provider:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\ManufacturerFormDataProvider'
    arguments:
      - '@prestashop.core.command_bus'
      - '@=service("prestashop.adapter.multistore_feature").isActive()'
      - '@=service("prestashop.adapter.shop.context").getShops(true, true)'

  prestashop.core.form.identifiable_object.data_provider.employee_form_data_provider:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\EmployeeFormDataProvider'
    arguments:
      - '@prestashop.core.query_bus'
      - '@=service("prestashop.adapter.multistore_feature").isActive()'
      - '@=service("prestashop.adapter.shop.context").getShops(true, true)'
      - '@=service("prestashop.adapter.employee.avatar_provider").getDefaultAvatarUrl()'

  prestashop.core.form.identifiable_object.data_provider.profile_form_data_provider:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\ProfileFormDataProvider'
    arguments:
      - '@prestashop.core.query_bus'
      - '@=service("prestashop.adapter.employee.avatar_provider").getDefaultAvatarUrl()'

  prestashop.core.form.identifiable_object.data_provider.cms_page_form_data_provider:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\CmsPageFormDataProvider'
    arguments:
      - '@prestashop.core.query_bus'
      - '@=service("prestashop.adapter.shop.context").getContextListShopID()'

  prestashop.core.form.identifiable_object.data_provider.supplier_form_data_provider:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\SupplierFormDataProvider'
    arguments:
      - '@prestashop.core.command_bus'
      - '@=service("prestashop.adapter.multistore_feature").isActive()'
      - '@=service("prestashop.adapter.shop.context").getShops(true, true)'
      - '@=service("prestashop.adapter.legacy.context").getContext().country.id'

  PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\AttributeGroupFormDataProvider:
    autowire: true
    public: false
    arguments:
      - '@prestashop.core.query_bus'

  prestashop.core.form.identifiable_object.data_provider.feature_form_data_provider:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\FeatureFormDataProvider'
    arguments:
      - '@prestashop.core.query_bus'
      - '@=service("prestashop.adapter.multistore_feature").isActive()'
      - '@=service("prestashop.adapter.shop.context").getShops(true, true)'

  PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\FeatureValueFormDataProvider:
    autowire: true
    public: false

  prestashop.core.form.identifiable_object.data_provider.order_message_form_data_provider:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\OrderMessageFormDataProvider'
    arguments:
      - '@prestashop.core.query_bus'

  prestashop.core.form.identifiable_object.data_provider.order_return_form_data_provider:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\OrderReturnFormDataProvider'
    arguments:
      - '@prestashop.core.query_bus'
      - '@prestashop.router'
      - '@translator'
      - '@=service("prestashop.adapter.legacy.context").getContext().language.date_format_lite'

  prestashop.core.form.identifiable_object.data_provider.catalog_price_rule_form_data_provider:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\CatalogPriceRuleFormDataProvider'
    arguments:
      - '@prestashop.core.command_bus'

  prestashop.core.form.identifiable_object.data_provider.attachment_form_data_provider:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\AttachmentFormDataProvider'
    arguments:
      - '@prestashop.core.query_bus'

  prestashop.core.form.identifiable_object.data_provider.cancel_product_form_data_provider:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\CancelProductFormDataProvider'
    arguments:
      - '@prestashop.core.query_bus'
      - '@prestashop.adapter.data_provider.currency'

  prestashop.core.form.identifiable_object.data_provider.address_form_data_provider:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\AddressFormDataProvider'
    arguments:
      - '@prestashop.core.query_bus'
      - '@=service("prestashop.adapter.legacy.context").getContext().country.id'

  prestashop.core.form.identifiable_object.data_provider.order_state_form_data_provider:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\OrderStateFormDataProvider'
    arguments:
      - '@prestashop.core.query_bus'

  prestashop.core.form.identifiable_object.data_provider.order_return_state_form_data_provider:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\OrderReturnStateFormDataProvider'
    arguments:
      - '@prestashop.core.query_bus'

  prestashop.core.form.identifiable_object.data_provider.product_form_data_provider:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\ProductFormDataProvider'
    arguments:
      - '@prestashop.core.query_bus'
      - '@prestashop.adapter.legacy.configuration'
      - '@=service("prestashop.adapter.legacy.context").getContext().language.id'
      - '@=service("prestashop.adapter.legacy.configuration").getInt("PS_SHOP_DEFAULT")'
      - "@=service('prestashop.adapter.shop.context').getContextShopID()"
      - '@prestashop.adapter.form.choice_provider.features_choice_provider'

  PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\ProductShopsFormDataProvider:
    autowire: true
    public: false
    arguments:
      $contextShopId: "@=service('prestashop.adapter.shop.context').getContextShopID()"

  prestashop.core.form.identifiable_object.data_provider.combination_form_data_provider:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\CombinationFormDataProvider'
    arguments:
      - '@prestashop.core.query_bus'
      - '@prestashop.adapter.shop.context'

  prestashop.core.form.identifiable_object.data_provider.bulk_combination_form_data_provider:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\BulkCombinationFormDataProvider'

  prestashop.core.form.identifiable_object.data_provider.empty_form_data_provider:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\EmptyFormDataProvider'

  prestashop.core.form.identifiable_object.data_provider.product_image_form_data_provider:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\ProductImageFormDataProvider'
    arguments:
      - '@prestashop.core.query_bus'
      - '@=service("prestashop.adapter.legacy.context").getContext().shop.id'

  prestashop.core.form.identifiable_object.data_provider.zone_form_data_provider:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\ZoneFormDataProvider'
    arguments:
      - '@prestashop.core.query_bus'
      - '@=service("prestashop.adapter.multistore_feature").isActive()'
      - '@=service("prestashop.adapter.shop.context").getShops(true, true)'

  prestashop.core.form.identifiable_object.data_provider.country_form_data_provider:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\CountryFormDataProvider'
    arguments:
      - '@prestashop.core.query_bus'
      - '@=service("prestashop.adapter.multistore_feature").isActive()'
      - '@=service("prestashop.adapter.shop.context").getShops(true, true)'

  prestashop.core.form.identifiable_object.data_provider.search_engine_form_data_provider:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\SearchEngineFormDataProvider'
    arguments:
      - '@prestashop.core.query_bus'

  prestashop.core.form.identifiable_object.data_provider.specific_price_form_data_provider:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\SpecificPriceFormDataProvider'
    arguments:
      - '@prestashop.core.query_bus'
      - "@=service('prestashop.adapter.legacy.context').getContext().shop.id"

  prestashop.core.form.identifiable_object.data_provider.state_form_data_provider:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\StateFormDataProvider'
    arguments:
      - '@prestashop.core.query_bus'
      - '@=service("prestashop.adapter.legacy.context").getContext().country.id'

  PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\TaxRulesGroupFormDataProvider:
    arguments:
      - '@prestashop.core.query_bus'

  PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\CartRuleFormDataProvider:
    autowire: true

  PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\TitleFormDataProvider:
    autowire: true

  PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\ApiAccessFormDataProvider:
    autowire: true
    public: false
