services:
    _defaults:
        public: true

    prestashop.admin.customer_preferences.form_handler:
        class: 'PrestaShopBundle\Form\Admin\ShopParameters\CustomerPreferences\CustomerPreferencesFormHandler'
        arguments:
            - '@form.factory'
            - '@prestashop.admin.customer_preferences.data_provider'
            - '@translator'
            - '@prestashop.hook.dispatcher'
            - '@prestashop.core.admin.tab.repository'
