parameters: ~
services:
    prestashop.adapter.hosting_information:
        class: 'PrestaShop\PrestaShop\Adapter\Hosting\HostingInformation'

    prestashop.adapter.shop_information:
        class: 'PrestaShop\PrestaShop\Adapter\Shop\ShopInformation'
        arguments: ['@prestashop.adapter.legacy.context']

    prestashop.adapter.mailing_information:
        class: 'PrestaShop\PrestaShop\Adapter\Mail\MailingInformation'

    prestashop.adapter.check_requirements:
        class: 'PrestaShop\PrestaShop\Adapter\Requirement\CheckRequirements'
        arguments: ['@translator']

    prestashop.adapter.check_missing_files:
        class: 'PrestaShop\PrestaShop\Adapter\Requirement\CheckMissingOrUpdatedFiles'