services:
  _defaults:
    public: true

  PrestaShop\PrestaShop\Adapter\Product\Customization\Validate\CustomizationFieldValidator:

  PrestaShop\PrestaShop\Adapter\Product\Customization\Repository\CustomizationFieldRepository:
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'
      - '@PrestaShop\PrestaShop\Adapter\Product\Customization\Validate\CustomizationFieldValidator'

  PrestaShop\PrestaShop\Adapter\Product\Customization\Update\CustomizationFieldDeleter:
    autowire: true
    public: false

  PrestaShop\PrestaShop\Adapter\Product\Customization\Update\ProductCustomizationFieldUpdater:
    autowire: true
    public: false

  PrestaShop\PrestaShop\Adapter\Product\Customization\QueryHandler\GetProductCustomizationFieldsHandler:
    arguments:
      - '@PrestaShop\PrestaShop\Adapter\Product\Customization\Repository\CustomizationFieldRepository'
    tags:
      - name: messenger.cqrs_handler
        command: PrestaShop\PrestaShop\Core\Domain\Product\Customization\Query\GetProductCustomizationFields

  PrestaShop\PrestaShop\Adapter\Product\Customization\CommandHandler\SetProductCustomizationFieldsHandler:
    arguments:
      - '@PrestaShop\PrestaShop\Adapter\Product\Customization\Repository\CustomizationFieldRepository'
      - '@PrestaShop\PrestaShop\Adapter\Product\Customization\Update\ProductCustomizationFieldUpdater'
    tags:
      - name: messenger.cqrs_handler
        command: PrestaShop\PrestaShop\Core\Domain\Product\Customization\Command\SetProductCustomizationFieldsCommand

  PrestaShop\PrestaShop\Adapter\Product\Customization\CommandHandler\RemoveAllCustomizationFieldsFromProductHandler:
    autowire: true
    public: false
    tags:
      - name: messenger.cqrs_handler
        command: PrestaShop\PrestaShop\Core\Domain\Product\Customization\Command\RemoveAllCustomizationFieldsFromProductCommand
