services:
    _defaults:
        public: true

    prestashop.adapter.product.virtual_product_file.command_handler.add_virtual_product_file_handler:
        class: PrestaShop\PrestaShop\Adapter\Product\VirtualProductFile\CommandHandler\AddVirtualProductFileHandler
        arguments:
            - '@prestashop.adapter.product.virtual_product_file.update.virtual_product_updater'
        tags:
            - name: tactician.handler
              command: PrestaShop\PrestaShop\Core\Domain\Product\VirtualProductFile\Command\AddVirtualProductFileCommand

    prestashop.adapter.product.virtual_product_file.update.virtual_product_updater:
        class: PrestaShop\PrestaShop\Adapter\Product\VirtualProductFile\Update\VirtualProductUpdater
        arguments:
            - '@prestashop.adapter.product.repository.product_repository'
            - '@prestashop.adapter.product.virtual_product_file.uploader.virtual_product_file_uploader'
            - '@prestashop.adapter.product.virtual_product_file.repository.product_download_repository'

    prestashop.adapter.product.virtual_product_file.validator.virtual_product_file_validator:
        class: PrestaShop\PrestaShop\Adapter\Product\VirtualProductFile\Validator\VirtualProductFileValidator
        arguments:
            - '@=service("prestashop.adapter.legacy.configuration").get("PS_ATTACHMENT_MAXIMUM_SIZE")'

    prestashop.adapter.product.virtual_product_file.uploader.virtual_product_file_uploader:
        class: PrestaShop\PrestaShop\Adapter\Product\VirtualProductFile\Uploader\VirtualProductFileUploader
        arguments:
            - '@prestashop.adapter.product.virtual_product_file.validator.virtual_product_file_validator'
            - !php/const _PS_DOWNLOAD_DIR_

    prestashop.adapter.product.virtual_product_file.validate.product_download_validator:
        class: PrestaShop\PrestaShop\Adapter\Product\VirtualProductFile\Validate\VirtualProductFileValidator

    prestashop.adapter.product.virtual_product_file.repository.product_download_repository:
        class: PrestaShop\PrestaShop\Adapter\Product\VirtualProductFile\Repository\VirtualProductFileRepository
        arguments:
            - '@prestashop.adapter.product.virtual_product_file.validate.product_download_validator'

    prestashop.adapter.product.virtual_product_file.command_handler.delete_virtual_product_file_handler:
        class: PrestaShop\PrestaShop\Adapter\Product\VirtualProductFile\CommandHandler\DeleteVirtualProductFileHandler
        tags:
            - name: tactician.handler
              command: PrestaShop\PrestaShop\Core\Domain\Product\VirtualProductFile\Command\DeleteVirtualProductFileCommand
