version: '2.1'

volumes:
  db-data:
  vendor:
  var:

services:
  mysql:
    image: mysql:5
    ports:
      - "3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: prestashop
      MYSQL_DATABASE: prestashop
    restart: always
  prestashop-git:
    build:
      dockerfile: .docker/Dockerfile
      context: .
      args:
        - VERSION=${VERSION:-8.1-apache}
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
        - NODE_VERSION=${NODE_VERSION:-14.21.3}
    environment:
      DISABLE_MAKE: ${DISABLE_MAKE:-0}
      PS_INSTALL_AUTO: ${PS_INSTALL_AUTO:-1}
      DB_PASSWD: ${DB_PASSWD:-prestashop}
      DB_NAME: ${DB_NAME:-prestashop}
      DB_SERVER: ${DB_SERVER:-mysql}
      DB_PREFIX: ${DB_PREFIX:-ps_}
      PS_DOMAIN: ${PS_DOMAIN:-localhost:8001}
      PS_FOLDER_INSTALL: ${PS_FOLDER_INSTALL:-install-dev}
      PS_FOLDER_ADMIN: ${PS_FOLDER_ADMIN:-admin-dev}
      PS_COUNTRY: ${PS_COUNTRY:-fr}
      PS_LANGUAGE: ${PS_LANGUAGE:-fr}
      PS_DEV_MODE: ${PS_DEV_MODE:-0}
      ADMIN_MAIL: ${ADMIN_MAIL:-demo@prestashop.com}
      ADMIN_PASSWD: ${ADMIN_PASSWD:-Correct Horse Battery Staple}
    command: ["/tmp/wait-for-it.sh", "--timeout=60", "--strict", "mysql:3306", "--", "/tmp/docker_run_git.sh"]
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www/html:delegated
