version: '2.1'

volumes:
  db-data:
  vendor:
  var:

services:
  mysql:
    image: mysql:5
    ports:
      - "3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: prestashop
      MYSQL_DATABASE: prestashop
    restart: always
  prestashop-git:
    build:
      dockerfile: .docker/Dockerfile
      context: .
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    environment:
      DISABLE_MAKE: ${DISABLE_MAKE:-0}
      PS_INSTALL_AUTO: ${PS_INSTALL_AUTO:-1}
      DB_PASSWD: ${DB_PASSWD:-prestashop}
      DB_NAME: ${DB_NAME:-prestashop}
      DB_SERVER: ${DB_SERVER:-mysql}
      PS_DOMAIN: ${PS_DOMAIN:-localhost:8001}
      PS_FOLDER_INSTALL: ${PS_FOLDER_INSTALL:-install-dev}
      PS_FOLDER_ADMIN: ${PS_FOLDER_ADMIN:-admin-dev}
    command: ["/tmp/wait-for-it.sh", "--timeout=60", "--strict", "mysql:3306", "--", "/tmp/docker_run_git.sh"]
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www/html/:delegated
