# todo uncomment all legacy links when page is finished.
admin_countries_index:
  path: /
  methods: GET
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\Improve\International\CountryController::indexAction'
    _legacy_controller: AdminCountries
#    _legacy_link: AdminCountries

admin_countries_search:
  path: /
  methods: POST
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\CommonController::searchGridAction
    gridDefinitionFactoryServiceId: prestashop.core.grid.definition.factory.country
    redirectRoute: admin_countries_index
    _legacy_controller: AdminCountries
#    _legacy_link: AdminCountries:submitFiltercountry

admin_countries_create:
  path: /new
  methods: [ GET, POST ]
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\Improve\International\CountryController::createAction'
    _legacy_controller: AdminCountries
#    _legacy_link: AdminCountries:addCountry

admin_countries_edit:
  path: /{countryId}/edit
  methods: [ GET, POST ]
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\Improve\International\CountryController::editAction'
    _legacy_controller: AdminCountry
    # _legacy_link: AdminCountry:updateCountry
    _legacy_parameters:
      id_country: countryId
  requirements:
    countryId: \d+
