admin_currencies_index:
    path: /
    methods: GET
    defaults:
        _controller: 'PrestaShopBundle:Admin\Improve\International\Currency:index'
        _legacy_controller: AdminCurrencies
        _legacy_link: AdminCurrencies

admin_currencies_search:
    path: /
    methods: POST
    defaults:
        _controller: 'PrestaShopBundle:Admin\Improve\International\Currency:search'
        _legacy_controller: AdminCurrencies
        _legacy_link: AdminCurrencies:submitFiltercurrency

admin_currencies_create:
    path: /new
    methods: [GET, POST]
    defaults:
        _controller: 'PrestaShopBundle:Admin\Improve\International\Currency:create'
        _legacy_controller: AdminCurrencies
        _legacy_link: AdminCurrencies:addcurrency

admin_currencies_edit:
    path: /{currencyId}/edit
    methods: [GET, POST]
    defaults:
        _controller: 'PrestaShopBundle:Admin\Improve\International\Currency:edit'
        _legacy_controller: AdminCurrencies
        _legacy_link: AdminCurrencies:updatecurrency
        _legacy_parameters:
          id_currency: currencyId
    requirements:
        currencyId: \d+

admin_currencies_delete:
    path: /{currencyId}/delete
    methods: DELETE
    defaults:
        _controller: 'PrestaShopBundle:Admin\Improve\International\Currency:delete'
        _legacy_controller: AdminCurrencies
        _legacy_link: AdminCurrencies:deletecurrency
        _legacy_parameters:
          id_currency: currencyId
    requirements:
        currencyId: \d+

admin_currencies_toggle_status:
    path: /{currencyId}/toggle-status
    methods: POST
    defaults:
        _controller: 'PrestaShopBundle:Admin\Improve\International\Currency:toggleStatus'
        _legacy_controller: AdminCurrencies
        _legacy_link: AdminCurrencies:statuscurrency
        _legacy_parameters:
          id_currency: currencyId
    requirements:
        currencyId: \d+

admin_currencies_update_live_exchange_rates:
    path: /update-live-exchange-rates
    methods: POST
    defaults:
        _controller: 'PrestaShopBundle:Admin\Improve\International\Currency:updateLiveExchangeRates'
        _legacy_controller: AdminCurrencies

admin_currencies_refresh_exchange_rates:
    path: /refresh-exchange-rates
    methods: POST
    defaults:
        _controller: 'PrestaShopBundle:Admin\Improve\International\Currency:refreshExchangeRates'
        _legacy_controller: AdminCurrencies
        _legacy_link: AdminCurrencies:SubmitExchangesRates

admin_currencies_get_reference_data:
  path: /reference-data/{currencyIsoCode}
  methods: GET
  defaults:
    _controller: 'PrestaShopBundle:Admin\Improve\International\Currency:getReferenceData'
    _legacy_controller: AdminCurrencies
    _legacy_link: AdminCurrencies:getReferenceData
