admin_carts_index:
  path: /
  methods: [ GET ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\Order\CartController::indexAction
    _legacy_controller: AdminCarts
    _legacy_link: AdminCarts
    _legacy_feature_flag: carts

admin_carts_search:
  path: /
  methods: [ POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\CommonController::searchGridAction
    gridDefinitionFactoryServiceId: prestashop.core.grid.definition.factory.cart
    redirectRoute: admin_carts_index
    _legacy_controller: AdminCarts
    _legacy_link: AdminCarts
    _legacy_feature_flag: carts

admin_carts_delete:
  path: /{cartId}
  methods: [ DELETE ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\Order\CartController::deleteCartAction
    _legacy_controller: AdminCarts
    _legacy_feature_flag: carts
  requirements:
    cartId: \d+

admin_carts_bulk_delete:
  path: /bulk-delete
  methods: [ POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\Order\CartController::bulkDeleteCartAction
    _legacy_controller: AdminCarts
    _legacy_link: AdminCarts
    _legacy_feature_flag: carts

admin_carts_export:
  path: /export
  methods: [ GET ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\Order\CartController::exportCartAction
    _legacy_controller: AdminCarts
    _legacy_link: AdminCarts:exportcart
    _legacy_feature_flag: carts

admin_carts_view:
  path: /{cartId}/view
  methods: [ GET ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\Order\CartController::viewAction
    _legacy_controller: AdminCarts
    _legacy_link: AdminCarts:viewcart
    _legacy_parameters:
      id_cart: cartId
  requirements:
    cartId: \d+
  options:
    expose: true

admin_carts_info:
  path: /{cartId}/info
  methods: [ GET ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\Order\CartController::getInfoAction
    _legacy_controller: AdminCarts
  requirements:
    cartId: \d+
  options:
    expose: true

admin_carts_create:
  path: /new
  methods: [ POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\Order\CartController::createAction
    _legacy_controller: AdminCarts
  options:
    expose: true

admin_carts_edit_addresses:
  path: /{cartId}/addresses
  methods: [ POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\Order\CartController::editAddressesAction
    _legacy_controller: AdminCarts
  requirements:
    cartId: \d+
  options:
    expose: true

admin_carts_edit_carrier:
  path: /{cartId}/carrier
  methods: [ POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\Order\CartController::editCarrierAction
    _legacy_controller: AdminCarts
  requirements:
    cartId: \d+
  options:
    expose: true

admin_carts_edit_currency:
  path: /{cartId}/currency
  methods: [ POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\Order\CartController::editCurrencyAction
    _legacy_controller: AdminCarts
  requirements:
    cartId: \d+
  options:
    expose: true

admin_carts_edit_language:
  path: /{cartId}/language
  methods: [ POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\Order\CartController::editLanguageAction
    _legacy_controller: AdminCarts
  requirements:
    cartId: \d+
  options:
    expose: true

admin_carts_set_delivery_settings:
  path: /{cartId}/rules/delivery-settings
  methods: [ POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\Order\CartController::updateDeliverySettingsAction
    _legacy_controller: AdminCarts
  requirements:
    cartId: \d+
  options:
    expose: true

admin_carts_add_cart_rule:
  path: /{cartId}/cart-rules
  methods: [ POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\Order\CartController::addCartRuleAction
    _legacy_controller: AdminCarts
  options:
    expose: true

admin_carts_delete_cart_rule:
  path: /{cartId}/cart-rules/{cartRuleId}/delete
  methods: [ POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\Order\CartController::deleteCartRuleAction
    _legacy_controller: AdminCarts
  options:
    expose: true

admin_carts_add_product:
  path: /{cartId}/products
  methods: [ POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\Order\CartController::addProductAction
    _legacy_controller: AdminCarts
  options:
    expose: true
  requirements:
    cartId: \d+

admin_carts_edit_product_price:
  path: /{cartId}/products/{productId}/price
  methods: [ POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\Order\CartController::editProductPriceAction
    _legacy_controller: AdminCarts
  options:
    expose: true
  requirements:
    cartId: \d+
    productId: \d+

admin_carts_edit_product_quantity:
  path: /{cartId}/products/{productId}/quantity
  methods: [ POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\Order\CartController::editProductQuantityAction
    _legacy_controller: AdminCarts
  options:
    expose: true
  requirements:
    cartId: \d+
    productId: \d+

admin_carts_delete_product:
  path: /{cartId}/delete-product
  methods: [ POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\Order\CartController::deleteProductAction
    _legacy_controller: AdminCarts
  options:
    expose: true
  requirements:
    cartId: \d+
