admin_carts_index:
  path: /
  methods: [GET]
  defaults:
    _controller: PrestaShopBundle:Admin/Sell/Order/Cart:index
    _legacy_controller: AdminCarts

admin_carts_view:
  path: /{cartId}/view
  methods: [GET]
  defaults:
    _controller: PrestaShopBundle:Admin/Sell/Order/Cart:view
    _legacy_controller: AdminCarts
  requirements:
    cartId: \d+

admin_carts_load_empty_customer_cart:
  path: /load-empty
  methods: [POST]
  defaults:
    _controller: PrestaShopBundle:Admin/Sell/Order/Cart:loadEmptyCustomerCart
    _legacy_controller: AdminCarts
  requirements:
    customerId: \d+
