#@todo: legacy links after page is fully migrated
admin_carts_index:
  path: /
  methods: [GET]
  defaults:
    _controller: PrestaShopBundle:Admin/Sell/Order/Cart:index
    _legacy_controller: AdminCarts

admin_carts_view:
  path: /{cartId}/view
  methods: [GET]
  defaults:
    _controller: PrestaShopBundle:Admin/Sell/Order/Cart:view
    _legacy_controller: AdminCarts
  requirements:
    cartId: \d+

admin_carts_info:
  path: /{cartId}/info
  methods: [GET]
  defaults:
    _controller: PrestaShopBundle:Admin/Sell/Order/Cart:getInfo
    _legacy_controller: AdminCarts
  requirements:
    cartId: \d+
  options:
    expose: true

admin_carts_create:
  path: /new
  methods: [POST]
  defaults:
    _controller: PrestaShopBundle:Admin/Sell/Order/Cart:create
    _legacy_controller: AdminCarts
  options:
    expose: true

admin_carts_edit_addresses:
  path: /{cartId}/addresses
  methods: [POST]
  defaults:
    _controller: PrestaShopBundle:Admin/Sell/Order/Cart:editAddresses
    _legacy_controller: AdminCarts
  requirements:
    cartId: \d+
  options:
    expose: true

admin_carts_edit_carrier:
  path: /{cartId}/carrier
  methods: [POST]
  defaults:
    _controller: PrestaShopBundle:Admin/Sell/Order/Cart:editCarrier
    _legacy_controller: AdminCarts
  requirements:
    cartId: \d+
  options:
    expose: true

admin_carts_set_free_shipping:
  path: /{cartId}/rules/free-shipping
  methods: [POST]
  defaults:
    _controller: PrestaShopBundle:Admin/Sell/Order/Cart:setFreeShipping
    _legacy_controller: AdminCarts
  requirements:
    cartId: \d+
  options:
    expose: true

admin_carts_add_rule:
  path: /{cartId}/rules/add
  methods: [POST]
  defaults:
    _controller: PrestaShopBundle:Admin/Sell/Order/Cart:addCartRuleToCart
    _legacy_controller: AdminCarts
  options:
    expose: true

admin_carts_delete_rule:
  path: /{cartId}/rules/{cartRuleId}/delete
  methods: [POST]
  defaults:
    _controller: PrestaShopBundle:Admin/Sell/Order/Cart:removeCartRuleFromCart
    _legacy_controller: AdminCarts
  options:
    expose: true

admin_add_product_for_order_creation:
  path: /add-product
  methods: [POST, GET]
  defaults:
    _controller: PrestaShopBundle:Admin/Sell/Order/Cart:addProduct
