admin_credit_slips_index:
  path: /
  methods: GET
  defaults:
    _controller: 'PrestaShopBundle:Admin/Sell/Order/CreditSlip:index'
    _legacy_controller: AdminSlip
#    _legacy_link: AdminSlip

admin_credit_slips_search:
  path: /
  methods: POST
  defaults:
    _controller: 'PrestaShopBundle:Admin/Sell/Order/CreditSlip:search'
    _legacy_controller: AdminSlip
    _legacy_link: AdminSlip:submitFilterslip

admin_credit_slips_pdf:
  path: /{creditSlipId}/pdf
  methods: GET
  defaults:
    _controller: 'PrestaShopBundle:Admin/Sell/Order/CreditSlip:generatePdf'
    _legacy_controller: AdminSlip
    _legacy_parameters:
      id_order_slip: creditSlipId
  requirements:
    creditSlipId: \d+

_admin_credit_slips_pdf_by_date:
  path: /pdf-by-date
  methods: GET
  defaults:
    _controller: 'PrestaShopBundle:Admin/Sell/Order/CreditSlip:generatePdfByDate'
    _legacy_controller: AdminSlip

admin_credit_slips_process_options:
  path: /options
  methods: [POST]
  defaults:
    _controller: 'PrestaShopBundle:Admin/Sell/Order/CreditSlip:processOptions'
    _legacy_controller: AdminSlip
    _legacy_link: AdminSlip:update
