admin_employees_index:
  path: /
  methods: [GET]
  defaults:
    _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Employee:index'
    _legacy_controller: AdminEmployees
    _legacy_link: AdminEmployees

admin_employees_search:
  path: /
  methods: [POST]
  defaults:
    _controller: 'PrestaShopBundle:Admin\Common:searchGrid'
    _legacy_controller: AdminEmployees
    _legacy_link: AdminEmployees:submitFilteremployee
    gridDefinitionFactoryServiceId: prestashop.core.grid.definition.factory.employee
    redirectRoute: admin_employees_index

admin_employees_save_options:
  path: /save-options
  methods: [POST]
  defaults:
    _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Employee:saveOptions'
    _legacy_controller: AdminEmployees
    _legacy_link: AdminEmployees:submitOptionsemployee

admin_employees_toggle_status:
  path: /{employeeId}/toggle-status
  methods: [POST]
  defaults:
    _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Employee:toggleStatus'
    _legacy_controller: AdminEmployees
    _legacy_link: AdminEmployees:statusemployee
    _legacy_parameters:
      id_employee: employeeId

admin_employees_bulk_enable_status:
  path: /bulk-enable-status
  methods: [POST]
  defaults:
    _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Employee:bulkStatusEnable'
    _legacy_controller: AdminEmployees
    _legacy_link: AdminEmployees:submitBulkenableSelectionemployee

admin_employees_bulk_disable_status:
  path: /bulk-disable-status
  methods: [POST]
  defaults:
    _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Employee:bulkStatusDisable'
    _legacy_controller: AdminEmployees
    _legacy_link: AdminEmployees:submitBulkdisableSelectionemployee

admin_employees_delete:
  path: /{employeeId}/delete
  methods: [POST]
  defaults:
    _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Employee:delete'
    _legacy_controller: AdminEmployees
    _legacy_link: AdminEmployees:deleteemployee
    _legacy_parameters:
      id_employee: employeeId

admin_employees_bulk_delete:
  path: /bulk-delete
  methods: [POST]
  defaults:
    _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Employee:bulkDelete'
    _legacy_controller: AdminEmployees
    _legacy_link: AdminEmployees:submitBulkdeleteemployee

admin_employees_create:
  path: /new
  methods: [GET,POST]
  defaults:
    _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Employee:create'
    _legacy_controller: AdminEmployees
    _legacy_link: AdminEmployees:addemployee

admin_employees_edit:
  path: /{employeeId}/edit
  methods: [GET,POST]
  defaults:
    _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Employee:edit'
    _legacy_controller: AdminEmployees
    _legacy_link: AdminEmployees:updateemployee
    _legacy_parameters:
      id_employee: employeeId
  requirements:
    employeeId: \d+

admin_employees_toggle_navigation:
  path: /toggle-navigation
  methods: [POST]
  defaults:
    _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Employee:toggleNavigationMenu'

admin_employees_change_form_language:
  path: /change-form-language
  methods: [POST]
  defaults:
    _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Employee:changeFormLanguage'

admin_employees_get_tabs:
  path: /tabs
  methods: [GET]
  defaults:
    _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Employee:getAccessibleTabs'
    _legacy_controller: AdminEmployees
