admin_employees_index:
  path: /
  methods: [GET]
  defaults:
    _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Employee:index'

admin_employees_save_options:
  path: /save-options
  methods: [POST]
  defaults:
    _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Employee:saveOptions'
