admin_permissions_index:
  path: /
  methods: [GET]
  defaults:
    _controller: PrestaShopBundle:Admin\Configure\AdvancedParameters\Permission:index
    _legacy_controller: AdminAccess

admin_permissions_update_tab_permissions:
  path: /update-tab-permissions
  methods: [POST]
  defaults:
    _controller: PrestaShopBundle:Admin\Configure\AdvancedParameters\Permission:updateTabPermissions
    _legacy_controller: AdminAccess

admin_permissions_update_module_permissions:
  path: /update-module-permissions
  methods: [POST]
  defaults:
    _controller: PrestaShopBundle:Admin\Configure\AdvancedParameters\Permission:updateModulePermissions
    _legacy_controller: AdminAccess
