admin_profiles_index:
    path: /
    methods: GET
    defaults:
        _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Profiles:index'
        _legacy_controller: AdminProfiles

admin_profiles_search:
    path: /
    methods: POST
    defaults:
        _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Profiles:search'
        _legacy_controller: AdminProfiles

admin_profiles_edit:
    path: /{profileId}/edit
    methods: GET
    defaults:
        _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Profiles:edit'
        _legacy_controller: AdminProfiles
    requirements:
        profileId: \d+

admin_profiles_delete:
    path: /{profileId}/delete
    methods: [POST]
    defaults:
        _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Profiles:delete'
        _legacy_controller: AdminProfiles
    requirements:
        profileId: \d+

admin_profiles_bulk_delete:
    path: /delete/bulk
    methods: [POST]
    defaults:
        _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Profiles:bulkDelete'
        _legacy_controller: AdminProfiles
