admin_products_index:
  path: /
  methods: GET
  defaults:
    _controller: 'PrestaShopBundle:Admin/Sell/Catalog/Product:index'
    _legacy_controller: AdminProducts

admin_products_search:
  path: /
  methods: POST
  defaults:
    _controller: PrestaShopBundle:Admin\Common:searchGrid
    _legacy_controller: AdminProducts
    gridDefinitionFactoryServiceId: prestashop.core.grid.definition.product
    redirectRoute: admin_products_index

admin_product_edit:
  path: /{productId}/edit
  methods: GET
  defaults:
    _controller: 'PrestaShopBundle:Admin/Sell/Catalog/Product:edit'
    _legacy_controller: AdminProducts
  requirements:
    productId: \d+

admin_product_edit_quantity:
  path: /{productId}/edit-quantity
  methods: GET
  defaults:
    _controller: 'PrestaShopBundle:Admin/Sell/Catalog/Product:editQuantity'
    _legacy_controller: AdminProducts
  requirements:
    productId: \d+

admin_product_edit_price:
  path: /{productId}/edit-price
  methods: GET
  defaults:
    _controller: 'PrestaShopBundle:Admin/Sell/Catalog/Product:editPrice'
    _legacy_controller: AdminProducts
  requirements:
    productId: \d+

admin_products_toggle_status:
  path: /{productId}/toggle-status
  methods: POST
  defaults:
    _controller: 'PrestaShopBundle:Admin/Sell/Catalog/Product:toggle'
    _legacy_controller: AdminProducts
  requirements:
    productId: \d+

admin_products_preview:
  path: /{productId}/preview
  methods: GET
  defaults:
    _controller: 'PrestaShopBundle:Admin/Sell/Catalog/Product:preview'
    _legacy_controller: AdminProducts
  requirements:
    productId: \d+

admin_products_edit:
  path: /{productId}/edit
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShopBundle:Admin/Sell/Catalog/Product:edit'
    _legacy_controller: AdminProducts
  requirements:
    productId: \d+

admin_products_duplicate:
  path: /{productId}/duplicate
  methods: [POST]
  defaults:
    _controller: 'PrestaShopBundle:Admin/Sell/Catalog/Product:duplicateProduct'
    _legacy_controller: AdminProducts
  requirements:
    productId: \d+

admin_products_delete:
  path: /{productId}/delete
  methods: DELETE
  defaults:
    _controller: 'PrestaShopBundle:Admin/Sell/Catalog/Product:delete'
    _legacy_controller: AdminProducts
  requirements:
    productId: \d+

admin_products_export:
  path: /export
  methods: GET
  defaults:
    _controller: 'PrestaShopBundle:Admin/Sell/Catalog/Product:export'
    _legacy_controller: AdminProducts

admin_products_bulk_enable_status:
  path: /bulk-enable-status
  methods: POST
  defaults:
    _controller: 'PrestaShopBundle:Admin/Sell/Catalog/Product:bulkEnable'
    _legacy_controller: AdminProducts

admin_products_bulk_disable_status:
  path: /bulk-disable-status
  methods: POST
  defaults:
    _controller: 'PrestaShopBundle:Admin/Sell/Catalog/Product:bulkDisable'
    _legacy_controller: AdminProducts

admin_products_bulk_delete:
  path: /bulk-delete
  methods: POST
  defaults:
    _controller: 'PrestaShopBundle:Admin/Sell/Catalog/Product:bulkDelete'
    _legacy_controller: AdminProducts
