admin_metas_index:
  path: /
  methods: GET
  defaults:
    _controller: 'PrestaShopBundle:Admin\Configure\ShopParameters\Meta:index'
    _legacy_controller: AdminMeta
    _legacy_link: AdminMeta

admin_metas_search:
  path: /
  methods: POST
  defaults:
    _controller: 'PrestaShopBundle:Admin\Configure\ShopParameters\Meta:search'
    _legacy_controller: AdminMeta
    _legacy_link: AdminMeta:submitFiltermeta

admin_metas_create:
  path: /new
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShopBundle:Admin\Configure\ShopParameters\Meta:create'
    _legacy_controller: AdminMeta
    _legacy_link: AdminMeta:addmeta

admin_metas_edit:
  path: /edit/{metaId}
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShopBundle:Admin\Configure\ShopParameters\Meta:edit'
    _legacy_controller: AdminMeta
    _legacy_link: AdminMeta:updatemeta

admin_metas_delete:
  path: /delete/{metaId}
  methods: DELETE
  defaults:
    _controller: 'PrestaShopBundle:Admin\Configure\ShopParameters\Meta:delete'
    _legacy_controller: AdminMeta
    _legacy_link: AdminLanguages:deletemeta

admin_metas_delete_bulk:
  path: /delete
  methods: POST
  defaults:
    _controller: 'PrestaShopBundle:Admin\Configure\ShopParameters\Meta:deleteBulk'
    _legacy_controller: AdminMeta
    _legacy_link: AdminLanguages:submitBulkdeletemeta

admin_metas_save_options:
  path: /options
  methods: [POST]
  defaults:
    _controller: 'PrestaShopBundle:Admin\Configure\ShopParameters\Meta:saveOptions'
    _legacy_controller: AdminMeta
    _legacy_link: AdminLanguages:submitOptionsmeta

admin_metas_generate_robots_text_file:
  path: /generate/robots
  methods: POST
  defaults:
    _controller: 'PrestaShopBundle:Admin\Configure\ShopParameters\Meta:generateRobotsFile'
    _legacy_controller: AdminMeta
    _legacy_link: AdminLanguages:submitRobots
