services:
  _defaults:
    public: false
    autowire: true

  PrestaShop\PrestaShop\Core\Domain\AuthorizationServer\Model\AuthorizedApplicationRepositoryInterface: '@PrestaShopBundle\Entity\Repository\AuthorizedApplicationRepository'
  PrestaShop\PrestaShop\Core\Domain\AuthorizationServer\Model\ApiAccessRepositoryInterface: '@PrestaShopBundle\Entity\Repository\ApiAccessRepository'

  PrestaShop\PrestaShop\Core\Domain\AuthorizationServer\CommandHandler\AddApplicationHandler:
    tags:
      - name: tactician.handler
        command: 'PrestaShop\PrestaShop\Core\Domain\AuthorizationServer\Command\AddApplicationCommand'

  PrestaShop\PrestaShop\Core\Domain\AuthorizationServer\CommandHandler\EditApplicationHandler:
    tags:
      - name: tactician.handler
        command: 'PrestaShop\PrestaShop\Core\Domain\AuthorizationServer\Command\EditApplicationCommand'

  PrestaShop\PrestaShop\Core\Domain\AuthorizationServer\QueryHandler\GetApplicationForEditingHandler:
    tags:
      - name: tactician.handler
        command: 'PrestaShop\PrestaShop\Core\Domain\AuthorizationServer\Query\GetApplicationForEditing'

  PrestaShop\PrestaShop\Core\Domain\AuthorizationServer\CommandHandler\DeleteApplicationHandler:
    tags:
      - name: tactician.handler
        command: 'PrestaShop\PrestaShop\Core\Domain\AuthorizationServer\Command\DeleteApplicationCommand'

  PrestaShopBundle\Model\AuthorizationServer\AuthorizedApplicationFactory: ~

  PrestaShop\PrestaShop\Core\Domain\AuthorizationServer\Model\AuthorizedApplicationFactoryInterface: '@PrestaShopBundle\Model\AuthorizationServer\AuthorizedApplicationFactory'
