services:
  _defaults:
    public: false
    autowire: true

  PrestaShop\PrestaShop\Core\Domain\AuthorizationServer\Model\AuthorizedApplicationRepositoryInterface: '@PrestaShopBundle\Entity\Repository\AuthorizedApplicationRepository'
  PrestaShop\PrestaShop\Core\Domain\AuthorizationServer\Model\ApiAccessRepositoryInterface: '@PrestaShopBundle\Entity\Repository\ApiAccessRepository'

  PrestaShop\PrestaShop\Core\Domain\AuthorizationServer\CommandHandler\AddApplicationHandler:
    autoconfigure: true

  PrestaShop\PrestaShop\Core\Domain\AuthorizationServer\CommandHandler\EditApplicationHandler:
    autoconfigure: true

  PrestaShop\PrestaShop\Core\Domain\AuthorizationServer\QueryHandler\GetApplicationForEditingHandler:
    autoconfigure: true

  PrestaShop\PrestaShop\Core\Domain\AuthorizationServer\CommandHandler\DeleteApplicationHandler:
    autoconfigure: true

  PrestaShopBundle\Model\AuthorizationServer\AuthorizedApplicationFactory: ~

  PrestaShop\PrestaShop\Core\Domain\AuthorizationServer\Model\AuthorizedApplicationFactoryInterface: '@PrestaShopBundle\Model\AuthorizationServer\AuthorizedApplicationFactory'

  PrestaShop\PrestaShop\Core\Domain\AuthorizationServer\QueryHandler\GetApplicationForViewingHandler:
    tags:
      - name: tactician.handler
        command: 'PrestaShop\PrestaShop\Core\Domain\AuthorizationServer\Query\GetApplicationForViewing'

  PrestaShop\PrestaShop\Core\Search\Builder\TypedBuilder\ApiAccessFiltersBuilder:
    class: 'PrestaShop\PrestaShop\Core\Search\Builder\TypedBuilder\ApiAccessFiltersBuilder'
    tags: [ 'core.typed_filters_builder' ]
