services:
  _defaults:
    public: true

  prestashop.bridge.helper.listing.helper_list_configuration_factory:
    class: PrestaShopBundle\Bridge\Helper\Listing\HelperListConfigurationFactory
    arguments:
      - '@prestashop.router'

  prestashop.bridge.helper.listing.filters_processor:
    class: PrestaShopBundle\Bridge\Helper\Listing\FiltersProcessor
    arguments:
      - "@prestashop.adapter.legacy.context"
      - "@prestashop.hook.dispatcher"

  prestashop.bridge.helper.listing.helper_bridge.helper_list_bridge:
    class: PrestaShopBundle\Bridge\Helper\Listing\HelperBridge\HelperListBridge
    arguments:
      - '@prestashop.adapter.legacy.context'
      - '@PrestaShopBundle\Service\DataProvider\UserProvider'
      - '@prestashop.hook.dispatcher'
      - '@prestashop.adapter.legacy.configuration'
      - '@PrestaShopBundle\Bridge\Smarty\BreadcrumbsAndTitleConfigurator'

  prestashop.bridge.helper.listing.helper_bridge.feature_helper_list_bridge:
    class: PrestaShopBundle\Bridge\Helper\Listing\HelperBridge\FeatureHelperListBridge
    parent: prestashop.bridge.helper.listing.helper_bridge.helper_list_bridge
    public: true
