blank_issues_enabled: false
contact_links:
  - name: ğŸš€ Idea / Feature request
    url: https://github.com/PrestaShop/PrestaShop/discussions/new?category=ideas
    about: Suggest an idea to improve PrestaShop
  - name: ğŸ™ I need help
    url: https://www.prestashop-project.org/support/
    about: If you have questions or need help
