admin_addresses_index:
  path: /
  methods: GET
  defaults:
    _controller: PrestaShopBundle:Admin\Sell\Address\Address:index
    _legacy_controller: AdminAddresses
#    _legacy_link: AdminAddresses

admin_addresses_filter:
  path: /
  methods: [POST]
  defaults:
    _controller: PrestaShopBundle:Admin\Common:searchGrid
    _legacy_controller: AdminAddresses
    gridDefinitionFactoryServiceId: prestashop.core.grid.definition.factory.address
    redirectRoute: admin_addresses_index
    #_legacy_link: AdminAddresses:submitFilteraddress

admin_addresses_create:
  path: /new
  methods: [GET, POST]
  defaults:
    _controller: PrestaShopBundle:Admin\Sell\Address\Address:create
    _legacy_controller: AdminAddresses
    #_legacy_link: AdminAddresses:addaddress

admin_addresses_edit:
  path: /{addressId}/edit
  methods: [GET, POST]
  defaults:
    _controller: PrestaShopBundle:Admin\Sell\Address\Address:edit
    _legacy_controller: AdminAddresses
    #_legacy_link: AdminAddresses:updateaddress
    _legacy_parameters:
      id_address: addressId
  requirements:
    addressId: \d+

admin_addresses_delete_bulk:
  path: /delete-bulk
  methods: [POST]
  defaults:
    _controller: PrestaShopBundle:Admin\Sell\Address\Address:deleteBulk
    _legacy_controller: AdminAddresses
    #_legacy_link: AdminAddresses:submitBulkdeleteaddress

admin_addresses_delete:
  path: /{addressId}/delete
  methods: [POST]
  defaults:
    _controller: PrestaShopBundle:Admin\Sell\Address\Address:delete
    _legacy_controller: AdminAddresses
    #_legacy_link: AdminAddresses:deleteaddress
    _legacy_parameters:
      id_address: addressId
  requirements:
    addressId: \d+

admin_addresses_save_required_fields:
  path: /save-required-fields
  methods: POST
  defaults:
    _controller: PrestaShopBundle:Admin\Sell\Address\Address:saveRequiredFields
    _legacy_controller: AdminAddresses
#    _legacy_link: AdminAddresses:submitFields
