api_translation_domains_tree:
    path: /translation/tree/{lang}/{type}/{selected}
    methods: [GET]
    defaults:
        _controller: prestashop.core.api.translation.controller:listTreeAction
        selected: false

api_translation_domain_catalog:
    path: /translation/{locale}/{domain}
    methods: [GET]
    defaults:
        _controller: prestashop.core.api.translation.controller:listDomainTranslationAction

api_translation_value_edit:
    path: /translation/{locale}/{domain}/edit
    methods: [POST]
    defaults:
        _controller: prestashop.core.api.translation.controller:translationEditAction

api_translation_value_reset:
    path: /translation/{locale}/{domain}/reset
    methods: [POST]
    defaults:
        _controller: prestashop.core.api.translation.controller:translationResetAction
