admin_category_listing:
    path: /
    methods: [GET, POST]
    defaults:
        _controller: PrestaShopBundle:Admin\Sell\Catalog\Category:index
        _legacy_controller: AdminCategories

admin_category_listing_search:
    path: /search
    methods: [POST]
    defaults:
        _controller: PrestaShopBundle:Admin\Common:searchGrid
        gridDefinitionFactoryService: prestashop.core.grid.definition.factory.category
        redirectRoute: admin_category_listing
        redirectQueryParamsToKeep:
            - 'id_category'

admin_category_process_bulk_status_enable:
    path: /bulk-status-enable
    methods: [POST]
    defaults:
        _controller: PrestaShopBundle:Admin\Sell\Catalog\Category:processBulkStatusEnable
        _legacy_controller: AdminCategories

admin_category_process_bulk_status_disable:
    path: /bulk-status-disable
    methods: [POST]
    defaults:
        _controller: PrestaShopBundle:Admin\Sell\Catalog\Category:processBulkStatusDisable
        _legacy_controller: AdminCategories

admin_category_process_status_toggle:
    path: /toggle-status/{categoryId}
    methods: [POST]
    defaults:
        _controller: PrestaShopBundle:Admin\Sell\Catalog\Category:processStatusToggle
        _legacy_controller: AdminCategories

admin_category_process_bulk_delete:
    path: /bulk-delete
    methods: [POST]
    defaults:
        _controller: PrestaShopBundle:Admin\Sell\Catalog\Category:processBulkDelete
        _legacy_controller: AdminCategories

admin_category_process_delete:
    path: /delete
    methods: [POST]
    defaults:
        _controller: PrestaShopBundle:Admin\Sell\Catalog\Category:processDelete
        _legacy_controller: AdminCategories

admin_category_export:
    path: /export
    methods: [GET]
    defaults:
      _controller: PrestaShopBundle:Admin\Sell\Catalog\Category:export
      _legacy_controller: AdminCategories

admin_category_add:
    path: /new
    methods: [GET, POST]
    defaults:
        _controller: PrestaShopBundle:Admin\Sell\Catalog\Category:add
        _legacy_controller: AdminCategories

admin_category_add_root:
    path: /new-root
    methods: [GET, POST]
    defaults:
        _controller: PrestaShopBundle:Admin\Sell\Catalog\Category:addRoot
        _legacy_controller: AdminCategories

admin_category_edit:
    path: /{categoryId}/edit
    methods: [GET, POST]
    defaults:
        _controller: PrestaShopBundle:Admin\Sell\Catalog\Category:edit
        _legacy_controller: AdminCategories
    requirements:
        categoryId: \d+

admin_category_edit_root:
    path: /{categoryId}/edit-root
    methods: [GET, POST]
    defaults:
        _controller: PrestaShopBundle:Admin\Sell\Catalog\Category:editRoot
        _legacy_controller: AdminCategories
    requirements:
        categoryId: \d+
