admin_manufacturers_create:
    path: /add
    methods: [GET, POST]
    defaults:
        _controller: 'PrestaShopBundle:Admin/Sell/Catalog/Manufacturer:createManufacturer'
        _legacy_controller: AdminManufacturers

admin_manufacturers_view:
    path: /{manufacturerId}/view
    methods: GET
    defaults:
        _controller: 'PrestaShopBundle:Admin/Sell/Catalog/Manufacturer:viewManufacturer'
        _legacy_controller: AdminManufacturers
    requirements:
        manufacturerId: \d+

admin_manufacturers_edit:
    path: /{manufacturerId}/edit
    methods: [GET, POST]
    defaults:
        _controller: 'PrestaShopBundle:Admin/Sell/Catalog/Manufacturer:editManufacturer'
        _legacy_controller: AdminManufacturers
    requirements:
        manufacturerId: \d+

admin_manufacturers_delete:
    path: /{manufacturerId}/delete
    methods: DELETE
    defaults:
        _controller: 'PrestaShopBundle:Admin/Sell/Catalog/Manufacturer:deleteManufacturer'
        _legacy_controller: AdminManufacturers
    requirements:
        manufacturerId: \d+

admin_manufacturers_bulk_delete:
    path: /bulk-delete
    methods: POST
    defaults:
        _controller: 'PrestaShopBundle:Admin/Sell/Catalog/Manufacturer:bulkDeleteManufacturer'

admin_manufacturers_bulk_enable:
    path: /bulk-enable
    methods: POST
    defaults:
        _controller: 'PrestaShopBundle:Admin/Sell/Catalog/Manufacturer:bulkEnableManufacturer'
        _legacy_controller: AdminManufacturers

admin_manufacturers_bulk_disable:
    path: /bulk-disable
    methods: POST
    defaults:
        _controller: 'PrestaShopBundle:Admin/Sell/Catalog/Manufacturer:bulkDisableManufacturer'
        _legacy_controller: AdminManufacturers

admin_manufacturers_toggle_status:
    path: /{manufacturerId}/toggle-status
    methods: POST
    defaults:
        _controller: 'PrestaShopBundle:Admin/Sell/Catalog/Manufacturer:toggleManufacturerStatus'
        _legacy_controller: AdminManufacturers
    requirements:
        manufacturerId: \d+

admin_manufacturers_export:
    path: /export
    methods: GET
    defaults:
        _controller: 'PrestaShopBundle:Admin/Sell/Catalog/Manufacturer:exportManufacturer'
        _legacy_controller: AdminManufacturers
