admin_manufacturers_index:
  path: /
  methods: GET
  defaults:
    _controller: 'PrestaShopBundle:Admin/Sell/Catalog/Manufacturer:index'
    _legacy_controller: AdminManufacturers
#   @todo:Implement legacy links at the end of whole page migration

#
# Manufacturer routes
#
admin_manufacturers_search:
  path: /
  methods: POST
  defaults:
    _controller: 'PrestaShopBundle:Admin/Sell/Catalog/Manufacturer:search'
    _legacy_controller: AdminManufacturers

admin_manufacturers_create:
  path: /new
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShopBundle:Admin/Sell/Catalog/Manufacturer:create'
    _legacy_controller: AdminManufacturers

admin_manufacturers_view:
  path: manufacturers/{manufacturerId}/view
  methods: GET
  defaults:
    _controller: 'PrestaShopBundle:Admin/Sell/Catalog/Manufacturer:view'
    _legacy_controller: AdminManufacturers
  requirements:
    manufacturerId: \d+

admin_manufacturers_edit:
  path: /{manufacturerId}/edit
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShopBundle:Admin/Sell/Catalog/Manufacturer:edit'
    _legacy_controller: AdminManufacturers
  requirements:
    manufacturerId: \d+

admin_manufacturers_delete:
  path: manufacturers/{manufacturerId}/delete
  methods: POST
  defaults:
    _controller: 'PrestaShopBundle:Admin/Sell/Catalog/Manufacturer:delete'
    _legacy_controller: AdminManufacturers
  requirements:
    manufacturerId: \d+

admin_manufacturers_bulk_delete:
  path: manufacturers/bulk-delete
  methods: POST
  defaults:
    _controller: 'PrestaShopBundle:Admin/Sell/Catalog/Manufacturer:bulkDelete'
    _legacy_controller: AdminManufacturers

admin_manufacturers_bulk_enable_status:
  path: manufacturers/bulk-enable
  methods: POST
  defaults:
    _controller: 'PrestaShopBundle:Admin/Sell/Catalog/Manufacturer:bulkEnable'
    _legacy_controller: AdminManufacturers

admin_manufacturers_bulk_disable_status:
  path: manufacturers/bulk-disable
  methods: POST
  defaults:
    _controller: 'PrestaShopBundle:Admin/Sell/Catalog/Manufacturer:bulkDisable'
    _legacy_controller: AdminManufacturers

admin_manufacturers_toggle_status:
  path: manufacturers/{manufacturerId}/toggle-status
  methods: POST
  defaults:
    _controller: 'PrestaShopBundle:Admin/Sell/Catalog/Manufacturer:toggleStatus'
    _legacy_controller: AdminManufacturers
  requirements:
    manufacturerId: \d+

admin_manufacturers_export:
  path: /export
  methods: GET
  defaults:
    _controller: 'PrestaShopBundle:Admin/Sell/Catalog/Manufacturer:export'
    _legacy_controller: AdminManufacturers

#
# Address routes
#
admin_manufacturer_addresses_create:
  path: addresses/new
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShopBundle:Admin/Sell/Catalog/Manufacturer:createAddress'
    _legacy_controller: AdminManufacturers

admin_manufacturer_addresses_edit:
  path: addresses/{addressId}/edit
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShopBundle:Admin/Sell/Catalog/Manufacturer:editAddress'
    _legacy_controller: AdminManufacturers
  requirements:
    addressId: \d+

admin_manufacturer_addresses_delete:
  path: addresses/{addressId}/delete
  methods: POST
  defaults:
    _controller: 'PrestaShopBundle:Admin/Sell/Catalog/Manufacturer:deleteAddress'
    _legacy_controller: AdminManufacturers
  requirements:
    addressId: \d+

admin_manufacturer_addresses_bulk_delete:
  path: addresses/bulk-delete
  methods: POST
  defaults:
    _controller: 'PrestaShopBundle:Admin/Sell/Catalog/Manufacturer:bulkDeleteAddress'
    _legacy_controller: AdminManufacturers

admin_manufacturer_addresses_export:
  path: addresses/export
  methods: GET
  defaults:
    _controller: 'PrestaShopBundle:Admin/Sell/Catalog/Manufacturer:exportAddress'
    _legacy_controller: AdminManufacturers
