_theme_catalog:
    resource: "theme_catalog.yml"
    prefix: /themes-catalog

_positions:
    resource: "positions.yml"
    prefix: /modules/positions

_theme:
    resource: "theme.yml"
    prefix: /themes

_cms_page:
    resource: "cms_pages.yml"
    prefix: /cms-pages
