_theme_catalog:
    resource: "theme_catalog.yml"
    prefix: /themes-catalog

_positions:
    resource: "positions.yml"
    prefix: /modules/positions

_theme:
    resource: "theme.yml"
    prefix: /theme

_cms_page:
    resource: "cms_page.yml"
    prefix: /cms-pages/{cmsCategoryParentId}
    requirements:
        cmsCategoryParentId: \d+
