_theme_catalog:
    resource: "theme_catalog.yml"
    prefix: /themes-catalog

_positions:
    resource: "positions.yml"
    prefix: /modules/positions

_theme:
    resource: "theme.yml"
    prefix: /themes

_cms_pages:
    resource: "cms_pages.yml"
    prefix: /cms-pages/{cmsCategoryParentId}
    requirements:
        cmsCategoryParentId: \d+
