admin_cms_pages_index:
    path: /
    methods: GET
    defaults:
        _controller: 'PrestaShopBundle:Admin\Improve\Design\CmsPage:index'
        _legacy_controller: AdminCmsContent

admin_cms_pages_search_cms_category:
    path: /category/search
    methods: POST
    defaults:
        _controller: 'PrestaShopBundle:Admin\Improve\Design\CmsPage:searchCategory'
        _legacy_controller: AdminCmsContent

admin_cms_pages_edit_cms_category:
    path: /category/{cmsCategoryId}/edit
    methods: [GET, POST]
    defaults:
        _controller: 'PrestaShopBundle:Admin\Improve\Design\CmsPage:editCmsCategory'
        _legacy_controller: AdminCmsContent
    requirements:
        cmsCategoryId: \d+

admin_cms_pages_delete_cms_category:
    path: /category/{cmsCategoryId}/delete
    methods: DELETE
    defaults:
        _controller: 'PrestaShopBundle:Admin\Improve\Design\CmsPage:deleteCmsCategory'
        _legacy_controller: AdminCmsContent
    requirements:
        cmsCategoryId: \d+

admin_cms_pages_delete_bulk_cms_category:
    path: /category/delete-bulk
    methods: POST
    defaults:
        _controller: 'PrestaShopBundle:Admin\Improve\Design\CmsPage:deleteBulkCmsCategory'
        _legacy_controller: AdminCmsContent

admin_cms_pages_toggle_cms_category:
    path: /category/{cmsCategoryId}/toggle-status
    methods: POST
    defaults:
        _controller: 'PrestaShopBundle:Admin\Improve\Design\CmsPage:toggleCmsCategory'
        _legacy_controller: AdminCmsContent
    requirements:
        cmsCategoryId: \d+

admin_cms_pages_bulk_status_enable:
    path: /category/bulk-enable-status
    methods: POST
    defaults:
        _controller: 'PrestaShopBundle:Admin\Improve\Design\CmsPage:bulkCmsPageStatusEnable'
        _legacy_controller: AdminCmsContent

admin_cms_pages_bulk_status_disable:
    path: /category/bulk-disable-status
    methods: POST
    defaults:
        _controller: 'PrestaShopBundle:Admin\Improve\Design\CmsPage:bulkCmsPageStatusDisable'
        _legacy_controller: AdminCmsContent

admin_cms_pages_update_position_cms_category:
    path: /category/{cmsCategoryId}/update-position
    methods: POST
    defaults:
        _controller: 'PrestaShopBundle:Admin\Improve\Design\CmsPage:updateCmsCategoryPosition'
        _legacy_controller: AdminCmsContent
    requirements:
        cmsCategoryId: \d+
