admin_cms_pages_index:
  path: /
  methods: GET
  defaults:
    _controller: 'PrestaShopBundle:Admin\Improve\Design\CmsPage:index'
    _legacy_controller: AdminCmsContent

admin_cms_pages_search_cms_category:
    path: /category/search
    methods: POST
    defaults:
        _controller: PrestaShopBundle:Admin\Common:searchGrid
        gridDefinitionFactoryServiceId: prestashop.core.grid.definition.factory.cms_page_category
        redirectRoute: admin_cms_pages_index
        redirectQueryParamsToKeep:
          - 'id_cms_category'

admin_cms_pages_category_search:
  path: /category/search
  methods: POST
  defaults:
    _controller: PrestaShopBundle:Admin\Common:searchGrid
    gridDefinitionFactoryService: prestashop.core.grid.definition.factory.cms_page_category
    redirectRoute: admin_cms_pages_index
    redirectQueryParamsToKeep:
      - 'id_cms_category'

admin_cms_pages_category_create:
  path: /category/new
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShopBundle:Admin\Improve\Design\CmsPage:createCmsCategory'
    _legacy_controller: AdminCmsContent

admin_cms_pages_category_edit:
  path: /category/{cmsCategoryId}/edit
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShopBundle:Admin\Improve\Design\CmsPage:editCmsCategory'
    _legacy_controller: AdminCmsContent
  requirements:
    cmsCategoryId: \d+

admin_cms_pages_category_delete:
  path: /category/{cmsCategoryId}/delete
  methods: DELETE
  defaults:
    _controller: 'PrestaShopBundle:Admin\Improve\Design\CmsPage:deleteCmsCategory'
    _legacy_controller: AdminCmsContent
  requirements:
    cmsCategoryId: \d+

admin_cms_pages_category_delete_bulk:
  path: /category/delete-bulk
  methods: POST
  defaults:
    _controller: 'PrestaShopBundle:Admin\Improve\Design\CmsPage:deleteBulkCmsCategory'
    _legacy_controller: AdminCmsContent

admin_cms_pages_category_toggle:
  path: /category/{cmsCategoryId}/toggle-status
  methods: POST
  defaults:
    _controller: 'PrestaShopBundle:Admin\Improve\Design\CmsPage:toggleCmsCategory'
    _legacy_controller: AdminCmsContent
  requirements:
    cmsCategoryId: \d+

admin_cms_pages_category_bulk_status_enable:
  path: /category/bulk-enable-status
  methods: POST
  defaults:
    _controller: 'PrestaShopBundle:Admin\Improve\Design\CmsPage:bulkCmsPageCategoryStatusEnableAction'
    _legacy_controller: AdminCmsContent

admin_cms_pages_category_bulk_status_disable:
  path: /category/bulk-disable-status
  methods: POST
  defaults:
    _controller: 'PrestaShopBundle:Admin\Improve\Design\CmsPage:bulkCmsPageCategoryStatusDisableAction'
    _legacy_controller: AdminCmsContent

admin_cms_pages_category_update_position:
  path: /category/update-position
  methods: POST
  defaults:
    _controller: 'PrestaShopBundle:Admin\Improve\Design\CmsPage:updateCmsCategoryPosition'
    _legacy_controller: AdminCmsContent

admin_cms_pages_toggle:
  path: /{cmsId}/toggle-status
  methods: POST
  defaults:
    _controller: 'PrestaShopBundle:Admin\Improve\Design\CmsPage:toggleCms'
    _legacy_controller: AdminCmsContent
  requirements:
    cmsId: \d+

admin_cms_pages_edit:
  path: /{cmsId}/edit
  methods: [GET,POST]
  defaults:
    _controller: 'PrestaShopBundle:Admin\Improve\Design\CmsPage:editCms'
    _legacy_controller: AdminCmsContent
  requirements:
    cmsId: \d+

admin_cms_pages_delete:
  path: /{cmsId}/delete
  methods: DELETE
  defaults:
    _controller: 'PrestaShopBundle:Admin\Improve\Design\CmsPage:deleteCms'
    _legacy_controller: AdminCmsContent
  requirements:
    cmsId: \d+
