admin_mail_theme_index:
  path: /
  methods: [GET]
  defaults:
    _controller: PrestaShopBundle:Admin\Improve\Design\MailTheme:index
    _legacy_controller: AdminMailTheme
    _legacy_link: AdminMailTheme

admin_mail_theme_generate:
  path: /generate
  methods: [POST]
  defaults:
    _controller: PrestaShopBundle:Admin\Improve\Design\MailTheme:generateMails
    _legacy_controller: AdminMailTheme
    _legacy_link: AdminMailTheme:postGenerateMails

admin_mail_theme_save_configuration:
  path: /saveConfiguration
  methods: [POST]
  defaults:
    _controller: PrestaShopBundle:Admin\Improve\Design\MailTheme:saveConfiguration
    _legacy_controller: AdminMailTheme
    _legacy_link: AdminMailTheme:saveConfiguration

admin_mail_theme_preview:
  path: /preview/{theme}
  methods: [GET]
  defaults:
    _controller: PrestaShopBundle:Admin\Improve\Design\MailTheme:previewTheme
    _legacy_controller: AdminMailTheme
    _legacy_link: AdminMailTheme:previewTheme

# Preview layout routes
admin_mail_theme_preview_layout:
  path: /preview/{locale}/{theme}/{layout}.{type}
  methods: [GET]
  defaults:
    _controller: PrestaShopBundle:Admin\Improve\Design\MailTheme:previewLayout
    _legacy_controller: AdminMailTheme
    _legacy_link: AdminMailTheme:previewLayout
    module: ''

admin_mail_theme_preview_module_layout:
  path: /preview/{locale}/{theme}/{module}/{layout}.{type}
  methods: [GET]
  defaults:
    _controller: PrestaShopBundle:Admin\Improve\Design\MailTheme:previewLayout
    _legacy_controller: AdminMailTheme
    _legacy_link: AdminMailTheme:previewModuleLayout

admin_mail_theme_raw_layout:
  path: /raw/{locale}/{theme}/{layout}.{type}
  methods: [GET]
  defaults:
    _controller: PrestaShopBundle:Admin\Improve\Design\MailTheme:rawLayout
    _legacy_controller: AdminMailTheme
    _legacy_link: AdminMailTheme:rawLayout
    module: ''

admin_mail_theme_raw_module_layout:
  path: /raw/{locale}/{theme}/{module}/{layout}.{type}
  methods: [GET]
  defaults:
    _controller: PrestaShopBundle:Admin\Improve\Design\MailTheme:rawLayout
    _legacy_link: AdminMailTheme:rawModuleLayout
    _legacy_controller: AdminMailTheme

admin_mail_theme_send_test_mail:
  path: /sendTestMail/{locale}/{theme}/{layout}
  methods: [GET]
  defaults:
    _controller: PrestaShopBundle:Admin\Improve\Design\MailTheme:sendTestMail
    _legacy_link: AdminMailTheme:rawModuleLayout
    _legacy_controller: AdminMailTheme
    module: ''

admin_mail_theme_send_test_module_mail:
  path: /sendTestMail/{locale}/{theme}/{module}/{layout}
  methods: [GET]
  defaults:
    _controller: PrestaShopBundle:Admin\Improve\Design\MailTheme:sendTestMail
    _legacy_link: AdminMailTheme:rawModuleLayout
    _legacy_controller: AdminMailTheme
