admin_theme_customize_page_layouts:
    path: /page-layout-customization
    methods: [GET, POST]
    defaults:
        _controller: PrestaShopBundle:Admin\Improve\Design\Theme:customizePageLayouts
        _legacy_controller: AdminThemes
