admin_themes_index:
  path: /
  methods: [GET]
  defaults:
    _controller: PrestaShopBundle:Admin\Improve\Design\Theme:index
    _legacy_controller: AdminThemes
    _legacy_link: AdminThemes

admin_themes_upload_logos:
  path: /upload-logos
  methods: [POST]
  defaults:
    _controller: PrestaShopBundle:Admin\Improve\Design\Theme:uploadLogos
    _legacy_controller: AdminThemes
    _legacy_link: AdminThemes:submitOptionsconfiguration

admin_themes_export_current:
  path: /export
  methods: [GET]
  defaults:
    _controller: PrestaShopBundle:Admin\Improve\Design\Theme:export
    _legacy_controller: AdminThemes
    _legacy_link: AdminThemes:exporttheme

admin_themes_import:
  path: /import
  methods: [GET, POST]
  defaults:
    _controller: PrestaShopBundle:Admin\Improve\Design\Theme:import
    _legacy_controller: AdminThemes
    _legacy_link: AdminThemes:importtheme

admin_themes_enable:
  path: /{themeName}/enable
  methods: [POST]
  defaults:
    _controller: PrestaShopBundle:Admin\Improve\Design\Theme:enable
    _legacy_controller: AdminThemes
    _legacy_link: AdminThemes:enableTheme
    _legacy_parameters:
      theme_name: themeName
  requirements:
    themeName: "^[a-zA-Z0-9_.-]+$"

admin_themes_delete:
  path: /{themeName}/delete
  methods: [POST]
  defaults:
    _controller: PrestaShopBundle:Admin\Improve\Design\Theme:delete
    _legacy_controller: AdminThemes
    _legacy_link: AdminThemes:deleteTheme
    _legacy_parameters:
      theme_name: themeName
  requirements:
    themeName: "^[a-zA-Z0-9_.-]+$"

admin_themes_adapt_to_rtl_languages:
  path: /adapt-to-rtl-languages
  methods: [POST]
  defaults:
    _controller: PrestaShopBundle:Admin\Improve\Design\Theme:adaptToRTLLanguages
    _legacy_controller: AdminThemes
    _legacy_link: AdminThemes:submitGenerateRTL
  requirements:
    themeName: "^[a-zA-Z0-9_.-]+$"

admin_theme_customize_layouts:
  path: /customize-layouts
  methods: [GET, POST]
  defaults:
    _controller: PrestaShopBundle:Admin\Improve\Design\Theme:customizeLayouts
    _legacy_controller: AdminThemes
    _legacy_link: AdminThemes:submitConfigureLayouts

admin_themes_reset_layouts:
  path: /{themeName}/reset-layouts
  methods: [POST]
  defaults:
    _controller: PrestaShopBundle:Admin\Improve\Design\Theme:resetLayouts
    _legacy_controller: AdminThemes
    _legacy_link: AdminThemes:resetToDefaults
    _legacy_parameters:
      theme_name: themeName
  requirements:
    themeName: "^[a-zA-Z0-9_.-]+$"
