admin_themes_index:
  path: /
  methods: [GET]
  defaults:
    _controller: PrestaShopBundle:Admin\Improve\Design\Theme:index
    _legacy_controller: AdminThemes

admin_themes_upload_logos:
  path: /upload-logos
  methods: [POST]
  defaults:
    _controller: PrestaShopBundle:Admin\Improve\Design\Theme:uploadLogos
    _legacy_controller: AdminThemes

admin_themes_export_current:
  path: /export
  methods: [GET]
  defaults:
    _controller: PrestaShopBundle:Admin\Improve\Design\Theme:export
    _legacy_controller: AdminThemes

admin_themes_import:
  path: /import
  methods: [GET, POST]
  defaults:
    _controller: PrestaShopBundle:Admin\Improve\Design\Theme:import
    _legacy_controller: AdminThemes

admin_themes_enable:
  path: /{themeName}/enable/
  methods: [POST]
  defaults:
    _controller: PrestaShopBundle:Admin\Improve\Design\Theme:enable
    _legacy_controller: AdminThemes
  requirements:
    themeName: "^[a-zA-Z0-9_.-]+$"

admin_themes_delete:
  path: /{themeName}/delete/
  methods: [POST]
  defaults:
    _controller: PrestaShopBundle:Admin\Improve\Design\Theme:delete
    _legacy_controller: AdminThemes
  requirements:
    themeName: "^[a-zA-Z0-9_.-]+$"

admin_theme_customize_page_layouts:
  path: /page-layout-customization
  methods: [GET, POST]
  defaults:
    _controller: PrestaShopBundle:Admin\Improve\Design\Theme:customizePageLayouts
    _legacy_controller: AdminThemes
