# All the Product related routes
admin_product_catalog:
    path: /catalog/{offset}/{limit}/{orderBy}/{sortOrder}
    methods:  [GET, POST]
    defaults:
        _controller: PrestaShopBundle\Controller\Admin\ProductController::catalogAction
        _legacy_controller: AdminProducts
        limit: last
        offset: 0
        orderBy: last
        sortOrder: last
    requirements:
        orderBy: last|id_product|name|reference|name_category|price|sav_quantity|position|active|position_ordering
        offset: last|\d+
        sortOrder: last|asc|desc

admin_product_list:
    path:     /list/{offset}/{limit}/{orderBy}/{sortOrder}
    methods:  [GET]
    defaults:
        _controller: PrestaShopBundle\Controller\Admin\ProductController::listAction
        limit: last
        offset: 0
        orderBy: last
        sortOrder: last
    requirements:
        orderBy: last|id_product|name|reference|name_category|price|sav_quantity|position|active|position_ordering
        offset: last|\d+
        sortOrder: last|asc|desc

admin_product_form:
    path: /form/{id}
    methods:  [GET, POST]
    defaults:
        id: 0
        _controller: PrestaShopBundle\Controller\Admin\ProductController::formAction
        _legacy_controller: AdminProducts
        _legacy_param_mapper_class: PrestaShop\PrestaShop\Adapter\Product\AdminProductDataProvider
        _legacy_param_mapper_method: mapLegacyParametersProductForm
    requirements:
        id: \d+

admin_product_use_legacy_setter:
    path:     /uselegacy/{use}
    methods:  [GET, POST]
    defaults:
        _controller: PrestaShopBundle\Controller\Admin\ProductController::shouldUseLegacyPagesAction
    requirements:
        use: 0|1

admin_product_bulk_action:
    path:     /bulk/{action}
    methods:  [POST]
    defaults:
        _controller: PrestaShopBundle\Controller\Admin\ProductController::bulkAction
    requirements:
        action: activate_all|deactivate_all|delete_all|duplicate_all

admin_product_unit_action:
    path:     /unit/{action}/{id}
    methods:  [POST]
    defaults:
        _controller: PrestaShopBundle\Controller\Admin\ProductController::unitAction
    requirements:
        action: delete|duplicate
        id: \d+

admin_product_mass_edit_action:
    path:     /massedit/{action}
    methods:  [POST]
    defaults:
        _controller: PrestaShopBundle\Controller\Admin\ProductController::massEditAction
    requirements:
        action: sort

admin_product_virtual_save_action:
    path:     /product/virtual/form/save/{idProduct}
    methods:  [POST]
    defaults:
        _controller: PrestaShopBundle\Controller\Admin\VirtualProductController::saveAction
        idProduct: 0
    requirements:
        idProduct: \d+

admin_product_virtual_remove_file_action:
    path:     /product/virtual/remove/file/{idProduct}
    defaults:
        _controller: PrestaShopBundle\Controller\Admin\VirtualProductController::removeFileAction
        idProduct: 0
    requirements:
        idProduct: \d+

admin_product_virtual_remove_action:
    path:     /product/virtual/remove/{idProduct}
    defaults:
        _controller: PrestaShopBundle\Controller\Admin\VirtualProductController::removeAction
        idProduct: 0
    requirements:
        idProduct: \d+

admin_product_attachement_add_action:
    path:     /product/attachment/form/add/{idProduct}
    methods:  [POST]
    defaults:
        _controller: PrestaShopBundle\Controller\Admin\AttachementProductController::addAction
        idProduct: 0
    requirements:
        idProduct: \d+

admin_product_image_upload:
    path:     /product/image/upload/{idProduct}
    methods:  [POST]
    defaults:
        _controller: 'PrestaShopBundle\Controller\Admin\ProductController::uploadImageAction'
        idProduct: 0
    requirements:
        idProduct: \d+

admin_product_image_positions:
    path:     /product/image/positions
    methods:  [POST]
    defaults:
        _controller: 'PrestaShopBundle\Controller\Admin\ProductController::updateImagePositionAction'
