#All the module related routes
admin_module_catalog:
    path:     /catalog
    methods:  [GET]
    defaults:
        _controller: PrestaShopBundle\Controller\Admin\ModuleController::catalogAction
        _legacy_controller: AdminModules

admin_module_catalog_refresh:
    path:     /catalog/refresh/{category}/{keyword}
    methods:  [GET]
    defaults:
        category:
        keyword:
        _controller: PrestaShopBundle\Controller\Admin\ModuleController::refreshCatalogAction
        _legacy_controller: AdminModules

admin_module_catalog_post:
    path:     /catalog
    methods:  [GET]
    defaults:
        _controller: PrestaShopBundle\Controller\Admin\ModuleController::getPreferredModulesAction
        _legacy_controller: AdminModules

admin_module_manage:
    path:     /manage/{category}/{keyword}
    methods:  [GET]
    defaults:
        category:
        keyword:
        _controller: PrestaShopBundle\Controller\Admin\ModuleController::manageAction
        _legacy_controller: AdminModules

admin_module_manage_action:
    path:     /manage/action/{action}/{module_name}
    methods:  [POST]
    defaults:
        _controller: PrestaShopBundle\Controller\Admin\ModuleController::moduleAction
    requirements:
        action: install|uninstall|enable|disable|enable_mobile|disable_mobile|reset|upgrade

admin_module_configure_action:
    path:     /manage/action/configure/{module_name}
    methods:  [GET, POST]
    defaults:
        _controller: PrestaShopBundle\Controller\Admin\ModuleController::configureModuleAction
        _legacy_controller: AdminModules

admin_module_manage_action_bulk:
    path:     /manage/bulk/{action}
    methods:  [POST]
    defaults:
        _controller: PrestaShopBundle\Controller\Admin\ModuleController::moduleAction
    requirements:
        action: install|uninstall|configure|enable|disable|reset|upgrade

admin_module_manage_update_all:
    path:     /manage/update/all
    methods:  [POST]
    defaults:
        _controller: PrestaShopBundle\Controller\Admin\ModuleController::moduleAction

admin_module_import:
    path:     /import
    methods:  [POST]
    defaults:
        module_name:
        _controller: PrestaShopBundle\Controller\Admin\ModuleController::importModuleAction

admin_module_notification:
    path:     /notifications
    methods:  [GET]
    defaults:
        _controller: PrestaShopBundle\Controller\Admin\ModuleController::notificationAction
        _legacy_controller: AdminModules
