# All the Attributes related routes

admin_attribute_get_all:
    path:     /get-all-attributes
    methods:  [GET]
    defaults:
        _controller: PrestaShopBundle\Controller\Admin\AttributeController::getAllAttributesAction
        _format: json

admin_attribute_generator:
    path:     /generator
    methods:  [POST]
    defaults:
        _controller: PrestaShopBundle\Controller\Admin\AttributeController::attributesGeneratorAction

admin_delete_attribute:
    path:     /delete/{idAttribute}/{idProduct}
    methods:  [GET]
    defaults:
        _controller: PrestaShopBundle\Controller\Admin\AttributeController::deleteAttributeAction
        idAttribute: 0
        idProduct: 0
    requirements:
        idAttribute: \d+
        idProduct: \d+

admin_get_product_combinations:
    path:     /get-product-combinations/{idProduct}
    methods:  [GET]
    defaults:
        _controller: PrestaShopBundle\Controller\Admin\AttributeController::getProductCombinationsAction
        _format: json
        idProduct: 0
    requirements:
        idProduct: \d+
