# All the Attributes related routes

admin_attribute_get_all:
    path:     /get-all
    methods:  [GET]
    defaults:
        _controller: PrestaShopBundle\Controller\Admin\AttributeController::getAllAttributesAction
        _format: json

admin_attribute_generator:
    path:     /generator
    methods:  [POST]
    defaults:
        _controller: PrestaShopBundle\Controller\Admin\AttributeController::attributesGeneratorAction

admin_delete_attribute:
    path:     /{idProduct}
    methods:  [DELETE]
    defaults:
        _controller: PrestaShopBundle\Controller\Admin\AttributeController::deleteAttributeAction

admin_delete_all_attributes:
    path:     /delete-all/{idProduct}
    methods:  [GET]
    defaults:
        _controller: PrestaShopBundle\Controller\Admin\AttributeController::deleteAllAttributeAction
        idProduct: 0
    requirements:
        idProduct: \d+

admin_get_product_combinations:
    path:     /product-combinations/{idProduct}
    methods:  [GET]
    defaults:
        _controller: PrestaShopBundle\Controller\Admin\AttributeController::getProductCombinationsAction
        _format: json
        idProduct: 0
    requirements:
        idProduct: \d+

admin_get_form_images_combination:
    path:     /product-form-images/{idProduct}
    methods:  [GET]
    defaults:
        _controller: PrestaShopBundle\Controller\Admin\AttributeController::getFormImagesAction
        _format: json
        idProduct: 0
    requirements:
        idProduct: \d+
