# All the Category related routes

admin_category_simple_add_form:
    path:     /form/add/simple
    methods:  [POST]
    defaults:
        _controller: PrestaShopBundle\Controller\Admin\CategoryController::addSimpleCategoryFormAction