services:
    form.type.date_picker:
        class: PrestaShopBundle\Form\Admin\Type\DatePickerType
        tags:
          - { name: form.type }

    form.type.product.simple_category:
        class: PrestaShopBundle\Form\Admin\Category\SimpleCategory
        arguments:
            - "@translator"
            - "@prestashop.adapter.data_provider.category"
        tags:
            - { name: form.type }

    form.type.product.feature:
        class: PrestaShopBundle\Form\Admin\Feature\ProductFeature
        arguments:
            - "@translator"
            - "@prestashop.adapter.legacy.context"
            - "@router"
            - "@prestashop.adapter.data_provider.feature"
        tags:
            - { name: form.type }

    form.type.product.attachment:
        class: PrestaShopBundle\Form\Admin\Product\ProductAttachement
        arguments:
            - "@translator"
            - "@prestashop.adapter.legacy.context"
        tags:
            - { name: form.type }

    form.type.product.combination:
        class: PrestaShopBundle\Form\Admin\Product\ProductCombination
        arguments:
            - "@translator"
            - "@prestashop.adapter.legacy.context"
        tags:
            - { name: form.type }

    form.type.product.custom_field:
        class: PrestaShopBundle\Form\Admin\Product\ProductCustomField
        arguments:
            - "@translator"
            - "@prestashop.adapter.legacy.context"
        tags:
            - { name: form.type }

    form.type.product.information:
        class: PrestaShopBundle\Form\Admin\Product\ProductInformation
        arguments:
            - "@translator"
            - "@prestashop.adapter.legacy.context"
            - "@router"
            - "@prestashop.adapter.data_provider.category"
            - "@prestashop.adapter.data_provider.product"
            - "@prestashop.adapter.data_provider.feature"
            - "@prestashop.adapter.data_provider.manufacturer"
        tags:
            - { name: form.type }

    form.type.product.options:
        class: PrestaShopBundle\Form\Admin\Product\ProductOptions
        arguments:
            - "@translator"
            - "@prestashop.adapter.legacy.context"
            - "@prestashop.adapter.data_provider.product"
            - "@prestashop.adapter.data_provider.supplier"
            - "@prestashop.adapter.data_provider.currency"
            - "@prestashop.adapter.data_provider.attachment"
            - "@router"
        tags:
            - { name: form.type }

    form.type.product.price:
        class: PrestaShopBundle\Form\Admin\Product\ProductPrice
        arguments:
            - "@translator"
            - "@prestashop.adapter.data_provider.tax"
            - "@router"
            - "@prestashop.adapter.shop.context"
            - "@prestashop.adapter.data_provider.country"
            - "@prestashop.adapter.data_provider.currency"
            - "@prestashop.adapter.data_provider.group"
            - "@prestashop.adapter.legacy.context"
            - "@prestashop.adapter.data_provider.customer"
        tags:
            - { name: form.type }

    form.type.product.quantity:
        class: PrestaShopBundle\Form\Admin\Product\ProductQuantity
        arguments:
            - "@translator"
            - "@router"
            - "@prestashop.adapter.legacy.context"
        tags:
            - { name: form.type }

    form.type.product.seo:
        class: PrestaShopBundle\Form\Admin\Product\ProductSeo
        arguments:
            - "@translator"
            - "@prestashop.adapter.legacy.context"
        tags:
            - { name: form.type }

    form.type.product.shipping:
        class: PrestaShopBundle\Form\Admin\Product\ProductShipping
        arguments:
            - "@translator"
            - "@prestashop.adapter.legacy.context"
            - "@prestashop.adapter.data_provider.warehouse"
            - "@prestashop.adapter.data_provider.carrier"
        tags:
            - { name: form.type }

    form.type.product.specific_price:
        class: PrestaShopBundle\Form\Admin\Product\ProductSpecificPrice
        arguments:
            - "@router"
            - "@translator"
            - "@prestashop.adapter.shop.context"
            - "@prestashop.adapter.data_provider.country"
            - "@prestashop.adapter.data_provider.currency"
            - "@prestashop.adapter.data_provider.group"
            - "@prestashop.adapter.legacy.context"
            - "@prestashop.adapter.data_provider.customer"
        tags:
            - { name: form.type }

    form.type.product.supplier_combination:
        class: PrestaShopBundle\Form\Admin\Product\ProductSupplierCombination
        arguments:
            - "@translator"
            - "@prestashop.adapter.legacy.context"
            - "@prestashop.adapter.data_provider.currency"
        tags:
            - { name: form.type }

    form.type.product.virtual:
        class: PrestaShopBundle\Form\Admin\Product\ProductVirtual
        arguments:
            - "@translator"
            - "@prestashop.adapter.legacy.context"
        tags:
            - { name: form.type }

    form.type.product.warehouse_combination:
        class: PrestaShopBundle\Form\Admin\Product\ProductWarehouseCombination
        arguments:
            - "@translator"
            - "@prestashop.adapter.legacy.context"
        tags:
            - { name: form.type }
