name: Classic # The name must match the directory name
display_name: Classic
version: 1.0.0
author:
  name: "John Doe"
  email: "pub@prestashop.com"
  url: "http://www.prestashop.com"

meta:
  compatibility:
      from: 1.7.0.0
      to: ~
  available_layouts:
    # Users will be able to choose each page's layout
    # from the theme's settings page.
    # Layouts are automatically parsed from the templates/layouts
    # folder so this configuration key is optional,
    # but it allows designers to provide some more user friendly
    # info than just a filename.
    layout-full-width:
      name: Full width layout
      description: Ideal for product pages to maximize picture size
    layout-left-side-column:
      name: One small left column
      description: Great for CMS pages to show advertisements on the side

global_settings:
  # All the settings below are used as default settings
  # when the theme is enabled on a shop.
  configuration:
    # All configuration values below are set
    # when the theme is enabled.
    PS_QUICK_VIEW: false
    NEW_PRODUCTS_NBR: 4
    PS_PNG_QUALITY: 8
  modules:
    to_enable:
      # All modules below are enabled when
      # the theme is enabled (and installed if needed).
      # They are disabled when the theme is disabled.
      - my-custom-module
      - yippeeslider
    to_disable:
      # All modules below are disabled when the theme is enabled.
      # They are re-enabled when the theme is disabled.
      - homeslider
      - blockwishlist
  hooks:
    custom_hooks:
      - name: displayFooterBefore
        title: displayFooterBefore
        description: Add a widget area above the footer
    modules_to_hook:
      displayHeaderTop:
        # displayHeaderTop will have exactly the following
        # modules hooked to it, in the specified order.
        # Each module in this list will be unhooked
        # from all other display hooks it is hooked to.
        - blocklanguages
        - blockcurrencies
        - blockuserinfo
      displayHeaderMiddle:
        # displayHeaderMiddle will have whatever is currently hooked to it
        # kept hooked to it, and blocksearch will be appended
        # to the list (or moved to the end if already hooked there).
        - ~
        - blocksearch:
          - pagenotfound
      displayHeaderBottom:
        # displayHeaderBottom will have blocktopmenu and blockcart
        # prepended to it.
        - blocktopmenu
        - blockcart
        - ~
      displayFooter:
        - blocknewsletter
      displayLeftColumn:
        # blockcategories is hooked on all pages on displayLeftColumn
        - blockcategories
        # blocktags is hooked on displayLeftColumn on all pages
        # except "category" and "index"
        - blocktags:
            except_pages:
              - category
              - index

  image_types:
    # When theme will be enabled, all image types will be removed
    # Template must declare their image type.
    product_listing:
      width: 220
      height: 220
      scope: [products, categories, manufacturers, suppliers]
    large_banner:
      width: 960
      height: 400
      scope: [categories]


theme_settings:
  # All the settings below can be changed through
  # an interface in the theme's administration panel,
  # and only depend on the theme / shop combination.
  #
  # When this file is parsed by PrestaShop, this configuration
  # key (theme_settings) is copied to a file name settings_n.yml
  # where n is the id of the shop where the theme is installed.
  #
  # When configuration is changed through the interface, only the
  # settings_n.yml file is updated and theme.yml remains unchanged.

  # The layout to use for all pages
  default_layout: layout-full-width
  layouts:
    # Specific layout for some pages
    identity: layout-left-side-column
    order-confirmation: layout-left-side-column
