services:
  _defaults:
    public: true

  # Service aliases for backward campatibility
  prestashop.core.api.stockMovement.repository:
    alias: prestashop.core.api.stock_movement.repository

  prestashop.core.api.stockMovement.controller:
    alias: prestashop.core.api.stock_movement.controller

  prestashop.twig.extension.dataFormatter:
    alias: prestashop.twig.extension.data_formatter

  hashing:
    alias: prestashop.core.crypto.hashing

  hook_provider:
    alias: prestashop.adapter.legacy.hook

  theme_manager:
    alias: prestashop.core.addon.theme.theme_manager

  theme_validator:
    alias: prestashop.core.addon.theme.theme_validator

  PrestaShopBundle\Translation\TranslatorInterface:
    alias: translator
