imports:
    - { resource: core/import.yml }
    - { resource: core/configuration.yml }
    - { resource: core/search.yml }
    - { resource: core/addon.yml }
    - { resource: core/foundation.yml }
    - { resource: core/geolocation.yml }
