services:
  _defaults:
    public: true

  prestashop.bundle.dependency_injection.provider.grid_definition_service_ids:
    class: 'PrestaShopBundle\DependencyInjection\Provider\GridDefinitionServiceIdsProvider'

  prestashop.bundle.dependency_injection.provider.identifiable_object_form_builder_service_definition:
    class: 'PrestaShopBundle\DependencyInjection\Provider\IdentifiableObjectFormBuilderServiceDefinitionsProvider'
