imports:
  - { resource: form/*.yml }

services:
  _defaults:
    public: false
    autowire: true
    autoconfigure: true
    bind:
      $multistoreFeature: '@prestashop.adapter.feature.multistore'
      $defaultCurrencyId: '@=service("prestashop.adapter.legacy.configuration").get("PS_CURRENCY_DEFAULT")'
      $defaultLanguageId: '@=service("prestashop.adapter.legacy.configuration").get("PS_LANG_DEFAULT")'
      $formRenderer: '@twig.form.renderer'
      $flashBag: '@session.flash_bag'
      $addDisablingSwitchListener: '@form.event_listener.add_disabling_switch_listener'
      $locale: '@prestashop.core.localization.locale.context_locale'
      $multistoreController: '@prestashop.core.admin.multistore'
      $validate: "@prestashop.adapter.validate"
      $multiStoreContext: '@prestashop.adapter.shop.context'

  PrestaShopBundle\Form\:
    resource: "../../../../Form/{Extension,Validator,DataTransformer}/*"

  PrestaShopBundle\Form\FormCloner:
  PrestaShopBundle\Form\FormBuilderModifier:
  PrestaShopBundle\Service\Form\MultistoreCheckboxEnabler:

  PrestaShopBundle\Form\Admin\Improve\Design\Theme\PageLayoutCustomizationFormFactory:
    arguments:
      - '@form.factory'
      - '@prestashop.core.addon.theme.repository'
      - '@=service("prestashop.adapter.legacy.context").getContext().shop.theme.getName()'
