imports:
    - { resource: form/form_type.yml }
    - { resource: form/form_extension.yml }
    - { resource: form/form_handler.yml }
    - { resource: form/form_data_provider.yml }
    - { resource: form/form_builder.yml }
    - { resource: form/form_choice_provider.yml }
