services:
  _defaults:
    public: true

  prestashop.utils.zip_manager:
    class: PrestaShopBundle\Utils\ZipManager

  PrestaShopBundle\Utils\FloatParser:
    autowire: true

  prestashop.util.database.entity_schema_manager:
    class: PrestaShopBundle\Utils\Database\EntitySchemaManager
    arguments:
      - "@doctrine.orm.default_entity_manager"
