# Product Form
admin_product_new:
    path: /new
    methods:  [GET]
    defaults:
        _controller: PrestaShopBundle:Admin/Product:new

admin_product_form:
    path: /{id}
    methods:  [GET, POST]
    defaults:
        _controller: PrestaShopBundle:Admin/Product:form
        _legacy_controller: AdminProducts
        _legacy_param_mapper_class: PrestaShop\PrestaShop\Adapter\Product\AdminProductDataProvider
        _legacy_param_mapper_method: mapLegacyParametersProductForm
    requirements:
        id: \d+

admin_product_virtual_save_action:
    path:     /virtual/save/{idProduct}
    methods:  [POST]
    defaults:
        _controller: PrestaShopBundle:Admin/VirtualProduct:save
        idProduct: 0
    requirements:
        idProduct: \d+

admin_product_virtual_remove_file_action:
    path:     /virtual/remove-file/{idProduct}
    defaults:
        _controller: PrestaShopBundle:Admin/VirtualProduct:removeFile
        idProduct: 0
    requirements:
        idProduct: \d+

admin_product_virtual_download_file_action:
    path:     /virtual/download-file/{idProduct}
    defaults:
        _controller: PrestaShopBundle:Admin/VirtualProduct:downloadFile
        idProduct: 0
    requirements:
        idProduct: \d+

admin_product_virtual_remove_action:
    path:     /virtual/remove/{idProduct}
    defaults:
        _controller: PrestaShopBundle:Admin/VirtualProduct:remove
        idProduct: 0
    requirements:
        idProduct: \d+

admin_product_attachement_add_action:
    path:     /attachment/form/add/{idProduct}
    methods:  [POST]
    defaults:
        _controller: PrestaShopBundle:Admin/AttachementProduct:add
        idProduct: 0
    requirements:
        idProduct: \d+

admin_product_image_upload:
    path:     /image/upload/{idProduct}
    methods:  [POST]
    defaults:
        _controller: PrestaShopBundle:Admin/ProductImage:uploadImage
        idProduct: 0
    requirements:
        idProduct: \d+

admin_product_image_positions:
    path:     /image/positions
    methods:  [POST]
    defaults:
        _controller: PrestaShopBundle:Admin/ProductImage:updateImagePosition

admin_product_image_form:
    path:     image/form/{idImage}
    defaults:
        _controller: PrestaShopBundle:Admin/ProductImage:form
        idImage: 0
    requirements:
        idImage: \d+

admin_product_image_delete:
    path:     /image/delete/{idImage}
    defaults:
        _controller: PrestaShopBundle:Admin/ProductImage:delete
        idImage: 0
    requirements:
        idImage: \d+
