services:
  _defaults:
    public: true

  prestashop.core.attribute_group.attribute_group_view_data_provider:
    class: 'PrestaShop\PrestaShop\Core\AttributeGroup\AttributeGroupViewDataProvider'
    arguments:
      - '@prestashop.core.command_bus'
