services:
    _defaults:
        public: true

    # Cache adapter
    prestashop.static_cache.adapter:
        class: Symfony\Component\Cache\Adapter\ArrayAdapter
        tags:
          - { name: monolog.logger, channel: cache }
          - { name: cache.pool, clearer: cache.default_clearer }
        calls:
          - ['setLogger', ['@logger']]

    prestashop.core.cache.clearer.entire_cache_clearer:
        class: 'PrestaShop\PrestaShop\Core\Cache\Clearer\EntireCacheClearer'
        arguments:
            - '@prestashop.adapter.cache.clearer.symfony_cache_clearer'
            - '@prestashop.adapter.cache.clearer.smarty_cache_clearer'
            - '@prestashop.adapter.cache.clearer.media_cache_clearer'
            - '@prestashop.adapter.cache.clearer.media_cache_clearer'
            - '@prestashop.adapter.cache.clearer.class_index_cache_clearer'
