services:
    _defaults:
        public: true

    prestashop.core.form.choice_provider.language_by_id:
        class: 'PrestaShop\PrestaShop\Core\Form\ChoiceProvider\LanguageByIdChoiceProvider'
        arguments:
            - '@prestashop.adapter.data_provider.language'

    prestashop.core.form.choice_provider.country_by_id:
        class: 'PrestaShop\PrestaShop\Core\Form\ChoiceProvider\CountryByIdChoiceProvider'
        arguments:
            - '@=service("prestashop.adapter.legacy.context").getLanguage().id'
            - '@prestashop.adapter.data_provider.country'

    prestashop.core.form.choice_provider.currency_by_id:
        class: 'PrestaShop\PrestaShop\Core\Form\ChoiceProvider\CurrencyByIdChoiceProvider'
        arguments:
            - '@prestashop.adapter.data_provider.currency'

    prestashop.core.form.choice_provider.timezone_by_name:
        class: 'PrestaShop\PrestaShop\Core\Form\ChoiceProvider\TimezoneByNameChoiceProvider'
        arguments:
            - '@prestashop.core.admin.timezone.repository'

    prestashop.core.form.choice_provider.localization_pack_by_iso_code:
        class: 'PrestaShop\PrestaShop\Core\Form\ChoiceProvider\LocalizationPackByIsoCodeChoiceProvider'
        arguments:
            - '@prestashop.core.localization.pack.loader.remote'
            - '@prestashop.core.localization.pack.loader.local'
            - '@prestashop.adapter.legacy.configuration'
            - '@translator'

    prestashop.core.form.choice_provider.country_by_iso_code:
        class: 'PrestaShop\PrestaShop\Core\Form\ChoiceProvider\CountryByIsoCodeChoiceProvider'
        arguments:
            - '@=service("prestashop.adapter.legacy.context").getLanguage().id'
            - '@prestashop.adapter.data_provider.country'

    prestashop.core.form.choice_provider.payment_module_by_name:
        class: 'PrestaShop\PrestaShop\Core\Form\ChoiceProvider\PaymentModuleByNameChoiceProvider'
        arguments:
            - '@prestashop.adapter.module.payment_module_provider'

    prestashop.core.form.choice_provider.group_by_id:
        class: 'PrestaShop\PrestaShop\Core\Form\ChoiceProvider\GroupByIdChoiceProvider'
        arguments:
            - '@prestashop.adapter.data_provider.group'
            - '@=service("prestashop.adapter.legacy.context").getLanguage().id'

    prestashop.core.form.choice_provider.carrier_by_reference_id:
        class: 'PrestaShop\PrestaShop\Core\Form\ChoiceProvider\CarrierByReferenceChoiceProvider'
        arguments:
            - '@prestashop.adapter.data_provider.carrier'
            - '@=service("prestashop.adapter.legacy.context").getLanguage().id'
