services:
    _defaults:
        public: true

    prestashop.core.hook.dispatcher:
        class: 'PrestaShop\PrestaShop\Core\Hook\HookDispatcher'
        arguments:
            - '@prestashop.hook.dispatcher'

    prestashop.core.hook.provider.grid_definition_hook_by_service_ids_provider:
      class: PrestaShop\PrestaShop\Core\Hook\Provider\GridDefinitionHookByServiceIdsProvider
