services:
    _defaults:
        public: true

    # KPI Row presenter
    prestashop.core.kpi_row.presenter:
        class: PrestaShop\PrestaShop\Core\Kpi\Row\KpiRowPresenter

    # KPI Row factories
    prestashop.core.kpi_row.factory.translations_page:
        class: PrestaShop\PrestaShop\Core\Kpi\Row\KpiRowFactory
        arguments:
            - '@prestashop.adapter.kpi.enabled_languages'
            - '@prestashop.adapter.kpi.main_country'
            - '@prestashop.adapter.kpi.translations'
        tags: ['web-only']

    prestashop.core.kpi_row.factory.categories:
        class: PrestaShop\PrestaShop\Core\Kpi\Row\KpiRowFactory
        arguments:
          - '@prestashop.adapter.kpi.disabled_categories'
          - '@prestashop.adapter.kpi.empty_categories'
          - '@prestashop.adapter.kpi.top_category'
          - '@prestashop.adapter.kpi.average_products_in_category'
        tags: ['web-only']

    prestashop.core.kpi_row.factory.customers:
        class: PrestaShop\PrestaShop\Core\Kpi\Row\KpiRowFactory
        arguments:
            - '@prestashop.adapter.kpi.most_common_customers_gender'
            - '@prestashop.adapter.kpi.average_customer_age'
            - '@prestashop.adapter.kpi.order_per_customer'
            - '@prestashop.adapter.kpi.newsletter_registrations'
        tags: ['web-only']
