services:
  _defaults:
    public: true

  prestashop.core.security.folder_guard.vendor:
    class: 'PrestaShop\PrestaShop\Core\Security\HtaccessFolderGuard'
    arguments:
      - '%kernel.project_dir%/app/Resources/security/.htaccess.dist'

  PrestaShop\PrestaShop\Core\Security\AccessCheckerInterface:
    alias: 'PrestaShop\PrestaShop\Adapter\Security\Access'
    public: false
  PrestaShop\PrestaShop\Core\Security\EmployeePermissionProviderInterface:
    alias: 'PrestaShop\PrestaShop\Adapter\Security\Access'
    public: false

  PrestaShop\PrestaShop\Core\Security\OAuth2\TokenAuthenticator:
    public: false
    autowire: true
    arguments:
      - '@PrestaShop\PrestaShop\Core\Security\OAuth2\AuthorisationServerInterface'

  PrestaShop\PrestaShop\Core\Security\OAuth2\ApiRequestMatcher:
    public: false
