services:
    _defaults:
        public: true

    prestashop.core.sql_manager.exporter.sql_request:
        class: 'PrestaShop\PrestaShop\Core\SqlManager\Exporter\SqlRequestExporter'
        arguments:
            - '@prestashop.core.export.dir'
            - '@prestashop.core.command_bus.tactician_query_bus_adapter'

    prestashop.core.sql_manager.configuration.sql_request:
        class: 'PrestaShop\PrestaShop\Core\SqlManager\Configuration\SqlRequestConfiguration'
        arguments:
            - '@prestashop.core.command_bus.tactician_command_bus_adapter'
            - '@prestashop.core.command_bus.tactician_query_bus_adapter'
