services:
    _defaults:
        public: true

    prestashop.core.util.url.htaccess_file_checker:
        class: 'PrestaShop\PrestaShop\Core\Util\Url\HtaccessFileChecker'
        arguments:
            - '@=service("prestashop.adapter.legacy.configuration").get("_PS_ROOT_DIR_")'
