# System Information
admin_system_information:
    path: system_information
    methods: [GET]
    defaults:
        _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\SystemInformation:index'
        _legacy_controller: AdminInformation

admin_system_information_check_files:
    path: system_information/files
    methods: [POST]
    defaults:
        _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\SystemInformation:displayCheckFiles'
        _legacy_controller: AdminInformation
    condition: "request.isXmlHttpRequest()"

# Performance
admin_performance:
    path: performance
    methods: [GET]
    defaults:
        _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Performance:index'
        _legacy_controller: AdminPerformance

admin_performance_save:
    path: performance
    methods: [POST]
    defaults:
        _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Performance:processForm'
        _legacy_controller: AdminPerformance

admin_clear_cache:
    path: clear_cache
    methods: [GET]
    defaults:
        _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Performance:clearCache'
        _legacy_controller: AdminPerformance

admin_servers:
    path: memcache/servers
    methods: [GET]
    defaults:
        _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\MemcacheServer:list'
        _legacy_controller: AdminPerformance
    condition: 'request.isXmlHttpRequest()'

admin_servers_add:
    path: memcache/servers
    methods: [POST]
    defaults:
        _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\MemcacheServer:add'
        _legacy_controller: AdminPerformance
    condition: 'request.isXmlHttpRequest()'

admin_servers_delete:
    path: memcache/servers
    methods: [DELETE]
    defaults:
        _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\MemcacheServer:delete'
        _legacy_controller: AdminPerformance
    condition: 'request.isXmlHttpRequest()'

admin_servers_test:
    path: memcache/servers/test
    methods: [GET]
    defaults:
        _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\MemcacheServer:test'
        _legacy_controller: AdminPerformance
    condition: 'request.isXmlHttpRequest()'

# Administration
admin_administration:
    path: administration
    methods: [GET]
    defaults:
        _controller: 'PrestaShopBundle:Admin\AdvancedParameters\Administration:index'
        _legacy_controller: AdminAdminPreferences

admin_administration_save:
    path: administration
    methods: [POST]
    defaults:
        _controller: 'PrestaShopBundle:Admin\AdvancedParameters\Administration:processForm'
        _legacy_controller: AdminAdminPreferences

# Import
admin_import:
    path: /import
    methods: [GET]
    defaults:
        _controller: 'PrestaShopBundle:Admin\Configure\AdvancedParameters\Import:import'
        _legacy_controller: AdminImport
