services:
  _defaults:
    autowire: true
    public: false

  PrestaShop\PrestaShop\Adapter\Alias\Validate\AliasValidator: ~

  PrestaShop\PrestaShop\Adapter\Alias\Repository\AliasRepository:
    arguments:
      $connection: '@doctrine.dbal.default_connection'
      $dbPrefix: '%database_prefix%'

  PrestaShop\PrestaShop\Adapter\Alias\CommandHandler\AddAliasHandler:
    autoconfigure: true

  PrestaShop\PrestaShop\Adapter\Alias\QueryHandler\GetAliasForEditingHandler:
    autoconfigure: true

  PrestaShop\PrestaShop\Adapter\Alias\CommandHandler\DeleteAliasHandler:
    autoconfigure: true

  PrestaShop\PrestaShop\Adapter\Alias\CommandHandler\BulkDeleteAliasHandler:
    autoconfigure: true

  PrestaShop\PrestaShop\Adapter\Alias\CommandHandler\UpdateAliasStatusHandler:
    autoconfigure: true

  PrestaShop\PrestaShop\Adapter\Alias\CommandHandler\BulkUpdateAliasStatusHandler:
    autoconfigure: true

  PrestaShop\PrestaShop\Adapter\Alias\CommandHandler\UpdateAliasHandler:
    autoconfigure: true

  PrestaShop\PrestaShop\Adapter\Alias\QueryHandler\SearchForSearchTermHandler:
    tags:
      - name: tactician.handler
        command: PrestaShop\PrestaShop\Core\Domain\Alias\Query\SearchForSearchTerm
