services:
  _defaults:
    public: true

  prestashop.adapter.attachment.query_handler.get_attachment_handler:
  prestashop.adapter.attachment.command_handler.delete_attachment_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Attachment\CommandHandler\DeleteAttachmentHandler'
    tags:
      - { name: 'tactician.handler', command: 'PrestaShop\PrestaShop\Core\Domain\Attachment\Command\DeleteAttachmentCommand' }

  prestashop.adapter.attachment.command_handler.bulk_delete_attachment_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Attachment\CommandHandler\BulkDeleteAttachmentsHandler'
    tags:
      - { name: 'tactician.handler', command: 'PrestaShop\PrestaShop\Core\Domain\Attachment\Command\BulkDeleteAttachmentsCommand' }

  prestashop.adapter.attachment.query_handler.get_attachment_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Attachment\QueryHandler\GetAttachmentHandler'
    arguments:
      - !php/const _PS_DOWNLOAD_DIR_
    tags:
      - { name: 'tactician.handler', command: 'PrestaShop\PrestaShop\Core\Domain\Attachment\Query\GetAttachment' }

  prestashop.adapter.contact.query_handler.get_attachment_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Attachment\QueryHandler\GetAttachmentForEditingHandler'
    tags:
      - { name: 'tactician.handler', command: 'PrestaShop\PrestaShop\Core\Domain\Attachment\Query\GetAttachmentForEditing' }

  prestashop.adapter.attachment.uploader.attachment_file_uploader:
    class: 'PrestaShop\PrestaShop\Adapter\File\Uploader\AttachmentFileUploader'

  prestashop.adapter.attachment.command_handler.abstract_attachment_handler:
    abstract:  true
    class: 'PrestaShop\PrestaShop\Adapter\Attachment\CommandHandler\AbstractAttachmentHandler'
    calls:
      - ['setValidator', ['@validator']]

  prestashop.adapter.attachment.command_handler.edit_attachment_handler:
    public: true
    class: 'PrestaShop\PrestaShop\Adapter\Attachment\CommandHandler\EditAttachmentHandler'
    parent: 'prestashop.adapter.attachment.command_handler.abstract_attachment_handler'
    arguments:
      - '@prestashop.adapter.attachment.uploader.attachment_file_uploader'
    tags:
      - { name: 'tactician.handler', command: 'PrestaShop\PrestaShop\Core\Domain\Attachment\Command\EditAttachmentCommand' }

  prestashop.adapter.attachment.command_handler.create_attachment_handler:
    public: true
    class: 'PrestaShop\PrestaShop\Adapter\Attachment\CommandHandler\CreateAttachmentHandler'
    parent: 'prestashop.adapter.attachment.command_handler.abstract_attachment_handler'
    arguments:
      - '@prestashop.adapter.attachment.uploader.attachment_file_uploader'
    tags:
      - { name: 'tactician.handler', command: 'PrestaShop\PrestaShop\Core\Domain\Attachment\Command\CreateAttachmentCommand' }
