services:
  _defaults:
    public: true

  prestashop.adapter.cart.command_handler.create_empty_customer_cart_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Cart\CommandHandler\CreateEmptyCustomerCartHandler'
    tags:
      - name: tactician.handler
        command: 'PrestaShop\PrestaShop\Core\Domain\Cart\Command\CreateEmptyCustomerCartCommand'

  prestashop.adapter.cart.command_handler.update_cart_currency_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Cart\CommandHandler\UpdateCartCurrencyHandler'
    tags:
      - name: tactician.handler
        command: 'PrestaShop\PrestaShop\Core\Domain\Cart\Command\UpdateCartCurrencyCommand'

  prestashop.adapter.cart.command_handler.update_cart_language_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Cart\CommandHandler\UpdateCartLanguageHandler'
    tags:
      - name: tactician.handler
        command: 'PrestaShop\PrestaShop\Core\Domain\Cart\Command\UpdateCartLanguageCommand'

  prestashop.adapter.cart.command_handler.update_cart_addresses_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Cart\CommandHandler\UpdateCartAddressesHandler'
    tags:
      - name: tactician.handler
        command: 'PrestaShop\PrestaShop\Core\Domain\Cart\Command\UpdateCartAddressesCommand'

  prestashop.adapter.cart.command_handler.set_free_shipping_to_cart_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Cart\CommandHandler\SetFreeShippingToCartHandler'
    arguments:
      - '@translator'
      - '@prestashop.adapter.legacy.configuration'
    tags:
      - name: tactician.handler
        command: 'PrestaShop\PrestaShop\Core\Domain\Cart\Command\SetFreeShippingToCartCommand'
