services:
  _defaults:
    public: true

  prestashop.adapter.catalog_price_rule.command_handler.delete_catalog_price_rule_handler:
    class: 'PrestaShop\PrestaShop\Adapter\CatalogPriceRule\CommandHandler\DeleteCatalogPriceRuleHandler'
    tags:
      - name: 'messenger.cqrs_handler'
        command: 'PrestaShop\PrestaShop\Core\Domain\CatalogPriceRule\Command\DeleteCatalogPriceRuleCommand'

  prestashop.adapter.catalog_price_rule.command_handler.bulk_delete_catalog_price_rule_handler:
    class: 'PrestaShop\PrestaShop\Adapter\CatalogPriceRule\CommandHandler\BulkDeleteCatalogPriceRuleHandler'
    tags:
      - name: 'messenger.cqrs_handler'
        command: 'PrestaShop\PrestaShop\Core\Domain\CatalogPriceRule\Command\BulkDeleteCatalogPriceRuleCommand'

  prestashop.adapter.catalog_price_rule.command_handler.add_catalog_price_rule_handler:
    class: 'PrestaShop\PrestaShop\Adapter\CatalogPriceRule\CommandHandler\AddCatalogPriceRuleHandler'
    tags:
      - name: 'messenger.cqrs_handler'
        command: 'PrestaShop\PrestaShop\Core\Domain\CatalogPriceRule\Command\AddCatalogPriceRuleCommand'

  prestashop.adapter.catalog_price_rule.command_handler.edit_catalog_price_rule_handler:
    class: 'PrestaShop\PrestaShop\Adapter\CatalogPriceRule\CommandHandler\EditCatalogPriceRuleHandler'
    tags:
      - name: 'messenger.cqrs_handler'
        command: 'PrestaShop\PrestaShop\Core\Domain\CatalogPriceRule\Command\EditCatalogPriceRuleCommand'

  prestashop.adapter.catalog_price_rule.command_handler.get_catalog_price_rule_for_editing_handler:
    class: 'PrestaShop\PrestaShop\Adapter\CatalogPriceRule\QueryHandler\GetCatalogPriceRuleForEditingHandler'
    tags:
      - name: 'messenger.cqrs_handler'
        command: 'PrestaShop\PrestaShop\Core\Domain\CatalogPriceRule\Query\GetCatalogPriceRuleForEditing'

  prestashop.adapter.catalog_price_rule.query_handler.get_catalog_price_rule_list_for_product_handler:
    class: 'PrestaShop\PrestaShop\Adapter\CatalogPriceRule\QueryHandler\GetCatalogPriceRuleListForProductHandler'
    arguments:
      - '@prestashop.adapter.catalog_price_rule.repository.catalog_price_rule_repository'
    tags:
      - name: 'messenger.cqrs_handler'
        command: 'PrestaShop\PrestaShop\Core\Domain\CatalogPriceRule\Query\GetCatalogPriceRuleListForProduct'

  prestashop.adapter.catalog_price_rule.repository.catalog_price_rule_repository:
    class: PrestaShop\PrestaShop\Adapter\CatalogPriceRule\Repository\CatalogPriceRuleRepository
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'
