services:
    _defaults:
        public: true

    prestashop.adapter.cms_page_category.command_handler.delete_cms_page_category_handler:
        class: PrestaShop\PrestaShop\Adapter\CMS\PageCategory\CommandHandler\DeleteCmsPageCategoryHandler
        tags:
            - name: tactician.handler
              command: PrestaShop\PrestaShop\Core\Domain\CmsPageCategory\Command\DeleteCmsPageCategoryCommand

    prestashop.adapter.cms_page_category.command_handler.toggle_cms_page_category_status_handler:
        class: PrestaShop\PrestaShop\Adapter\CMS\PageCategory\CommandHandler\ToggleCmsPageCategoryStatusHandler
        tags:
            - name: tactician.handler
              command: PrestaShop\PrestaShop\Core\Domain\CmsPageCategory\Command\ToggleCmsPageCategoryStatusCommand

    prestashop.adapter.cms_page_category.command_handler.bulk_delete_cms_page_category_handler:
        class: PrestaShop\PrestaShop\Adapter\CMS\PageCategory\CommandHandler\BulkDeleteCmsPageCategoryHandler
        tags:
            - name: tactician.handler
              command: PrestaShop\PrestaShop\Core\Domain\CmsPageCategory\Command\BulkDeleteCmsPageCategoryCommand

    prestashop.adapter.cms_page.command_handler.bulk_enable_cms_page_category_handler:
        class: PrestaShop\PrestaShop\Adapter\CMS\PageCategory\CommandHandler\BulkEnableCmsPageCategoryHandler
        tags:
            - name: tactician.handler
              command: PrestaShop\PrestaShop\Core\Domain\CmsPageCategory\Command\BulkEnableCmsPageCategoryCommand

    prestashop.adapter.cms_page.command_handler.bulk_disable_cms_page_category_handler:
        class: PrestaShop\PrestaShop\Adapter\CMS\PageCategory\CommandHandler\BulkDisableCmsPageCategoryHandler
        tags:
            - name: tactician.handler
              command: PrestaShop\PrestaShop\Core\Domain\CmsPageCategory\Command\BulkDisableCmsPageCategoryCommand

