services:
  _defaults:
    public: true

  prestashop.adapter.cms_page.command_handler.bulk_disable_cms_page:
    class: PrestaShop\PrestaShop\Adapter\CMS\Page\CommandHandler\BulkDisableCmsPageHandler
    tags:
      - name: tactician.handler
        command: PrestaShop\PrestaShop\Core\Domain\CmsPage\Command\BulkDisableCmsPageCommand

  prestashop.adapter.cms_page.command_handler.bulk_enable_cms_page:
    class: PrestaShop\PrestaShop\Adapter\CMS\Page\CommandHandler\BulkEnableCmsPageHandler
    tags:
      - name: tactician.handler
        command: PrestaShop\PrestaShop\Core\Domain\CmsPage\Command\BulkEnableCmsPageCommand

  prestashop.adapter.cms_page.command_handler.toggle_cms_page_status:
    class: PrestaShop\PrestaShop\Adapter\CMS\Page\CommandHandler\ToggleCmsPageStatusHandler
