services:
  _defaults:
    public: true

  PrestaShop\PrestaShop\Adapter\Configuration: ~

  prestashop.adapter.legacy.configuration:
    alias: PrestaShop\PrestaShop\Adapter\Configuration

  PrestaShop\PrestaShop\Adapter\Tools: ~

  prestashop.adapter.tools:
    alias: PrestaShop\PrestaShop\Adapter\Tools
    deprecated:
      package: PrestaShop\PrestaShop
      version: 8.1

  PrestaShop\PrestaShop\Adapter\LegacyContext:
    arguments:
      - "%mail_themes_uri%"
      - '@PrestaShop\PrestaShop\Adapter\Tools'

  prestashop.adapter.legacy.context:
    alias: PrestaShop\PrestaShop\Adapter\LegacyContext

  prestashop.adapter.environment:
    class: PrestaShop\PrestaShop\Adapter\Environment
    arguments:
      - !php/const _PS_SYMFONY_DEBUG_
      - !php/const _PS_ENV_

  prestashop.adapter.validate:
    class: PrestaShop\PrestaShop\Adapter\Validate

  PrestaShop\PrestaShop\Adapter\ContextStateManager:
    arguments:
      - '@PrestaShop\PrestaShop\Adapter\LegacyContext'

  prestashop.adapter.context_state_manager:
    alias: PrestaShop\PrestaShop\Adapter\ContextStateManager

  PrestaShop\PrestaShop\Adapter\Employee\EmployeeRepository: ~
