services:
  _defaults:
    public: true

  prestashop.adapter.configuration.command_handler.switch_debug_mode_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Configuration\CommandHandler\SwitchDebugModeHandler'
    arguments:
      - '@prestashop.adapter.debug_mode'
    tags:
      - { name: messenger.cqrs_handler, command: PrestaShop\PrestaShop\Core\Domain\Configuration\Command\SwitchDebugModeCommand }
