services:
  _defaults:
    public: true

  prestashop.adapter.profile.employee.command_handler.toggle_employee_status_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Profile\Employee\CommandHandler\ToggleEmployeeStatusHandler'
    tags:
      - { name: tactician.handler, command: PrestaShop\PrestaShop\Core\Domain\Profile\Employee\Command\ToggleEmployeeStatusCommand }

  prestashop.adapter.profile.employee.command_handler.bulk_update_employee_status_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Profile\Employee\CommandHandler\BulkUpdateEmployeeStatusHandler'
    tags:
      - { name: tactician.handler, command: PrestaShop\PrestaShop\Core\Domain\Profile\Employee\Command\BulkUpdateEmployeeStatusCommand }

  prestashop.adapter.profile.employee.command_handler.delete_employee_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Profile\Employee\CommandHandler\DeleteEmployeeHandler'
    tags:
      - { name: tactician.handler, command: PrestaShop\PrestaShop\Core\Domain\Profile\Employee\Command\DeleteEmployeeCommand }

  prestashop.adapter.profile.employee.command_handler.bulk_delete_employee_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Profile\Employee\CommandHandler\BulkDeleteEmployeeHandler'
    tags:
      - { name: tactician.handler, command: PrestaShop\PrestaShop\Core\Domain\Profile\Employee\Command\BulkDeleteEmployeeCommand }

  prestashop.adapter.employee.query_handler.get_employee_for_editing:
    class: 'PrestaShop\PrestaShop\Adapter\Profile\Employee\QueryHandler\GetEmployeeForEditingHandler'
    tags:
      - { name: tactician.handler, command: PrestaShop\PrestaShop\Core\Domain\Profile\Employee\Query\GetEmployeeForEditing }

  prestashop.adapter.employee.form_access_checker:
    class: 'PrestaShop\PrestaShop\Adapter\Employee\EmployeeFormAccessChecker'
    arguments:
      - '@prestashop.adapter.data_provider.employee'
      - '@prestashop.core.admin.tab.repository'

  prestashop.adapter.employee.command_handler.add_employee_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Profile\Employee\CommandHandler\AddEmployeeHandler'
    arguments:
      - '@prestashop.core.crypto.hashing'
      - '@prestashop.core.employee.profile_access_checker'
    tags:
      - { name: tactician.handler, command: PrestaShop\PrestaShop\Core\Domain\Profile\Employee\Command\AddEmployeeCommand }

  prestashop.adapter.employee.command_handler.edit_employee_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Profile\Employee\CommandHandler\EditEmployeeHandler'
    arguments:
      - '@prestashop.core.crypto.hashing'
      - '@prestashop.core.employee.profile_access_checker'
      - '@prestashop.adapter.data_provider.employee'
      - '@prestashop.adapter.legacy.context'
    tags:
      - { name: tactician.handler, command: PrestaShop\PrestaShop\Core\Domain\Profile\Employee\Command\EditEmployeeCommand }

  prestashop.adapter.employee.default_avatar_provider:
    class: 'PrestaShop\PrestaShop\Adapter\Employee\DefaultAvatarProvider'
    arguments:
      - '@prestashop.adapter.tools'

  prestashop.adapter.employee.data_provider:
    class: 'PrestaShop\PrestaShop\Adapter\Employee\EmployeeDataProvider'
