services:
  _defaults:
    public: true
    bind:
      $connection: '@doctrine.dbal.default_connection'
      $dbPrefix: '%database_prefix%'

  PrestaShop\PrestaShop\Adapter\Feature\CommandHandler\AddFeatureHandler:
    autowire: true
    public: false
    tags:
      - name: tactician.handler
        command: PrestaShop\PrestaShop\Core\Domain\Feature\Command\AddFeatureCommand

  PrestaShop\PrestaShop\Adapter\Feature\CommandHandler\EditFeatureHandler:
    autowire: true
    public: false
    tags:
      - name: tactician.handler
        command: PrestaShop\PrestaShop\Core\Domain\Feature\Command\EditFeatureCommand

  PrestaShop\PrestaShop\Adapter\Feature\QueryHandler\GetFeatureForEditingHandler:
    tags:
      - name: tactician.handler
        command: PrestaShop\PrestaShop\Core\Domain\Feature\Query\GetFeatureForEditing

  PrestaShop\PrestaShop\Adapter\Feature\CommandHandler\AddFeatureValueHandler:
    arguments:
      - '@PrestaShop\PrestaShop\Adapter\Feature\Repository\FeatureRepository'
      - '@PrestaShop\PrestaShop\Adapter\Feature\Repository\FeatureValueRepository'
    tags:
      - name: tactician.handler
        command: PrestaShop\PrestaShop\Core\Domain\Feature\Command\AddFeatureValueCommand

  PrestaShop\PrestaShop\Adapter\Feature\CommandHandler\EditFeatureValueHandler:
    arguments:
      - '@PrestaShop\PrestaShop\Adapter\Feature\Repository\FeatureValueRepository'
    tags:
      - name: tactician.handler
        command: PrestaShop\PrestaShop\Core\Domain\Feature\Command\EditFeatureValueCommand

  PrestaShop\PrestaShop\Adapter\Feature\QueryHandler\GetFeatureValueForEditingHandler:
    arguments:
      - '@PrestaShop\PrestaShop\Adapter\Feature\Repository\FeatureValueRepository'
    tags:
      - name: tactician.handler
        command: PrestaShop\PrestaShop\Core\Domain\Feature\Query\GetFeatureValueForEditing

  PrestaShop\PrestaShop\Adapter\Feature\CommandHandler\DeleteFeatureHandler:
    autowire: true
    public: false
    tags:
      - name: tactician.handler
        command: PrestaShop\PrestaShop\Core\Domain\Feature\Command\DeleteFeatureCommand

  PrestaShop\PrestaShop\Adapter\Feature\CommandHandler\BulkDeleteFeatureHandler:
    autowire: true
    public: false
    tags:
      - name: tactician.handler
        command: PrestaShop\PrestaShop\Core\Domain\Feature\Command\BulkDeleteFeatureCommand

  PrestaShop\PrestaShop\Adapter\Feature\CommandHandler\DeleteFeatureValueHandler:
    autowire: true
    public: false
    tags:
      - name: tactician.handler
        command: PrestaShop\PrestaShop\Core\Domain\Feature\Command\DeleteFeatureValueCommand

  PrestaShop\PrestaShop\Adapter\Feature\CommandHandler\BulkDeleteFeatureValueHandler:
    autowire: true
    public: false
    tags:
      - name: tactician.handler
        command: PrestaShop\PrestaShop\Core\Domain\Feature\Command\BulkDeleteFeatureValueCommand

  PrestaShop\PrestaShop\Adapter\Feature\Repository\FeatureRepository:
    autowire: true
    public: false

  PrestaShop\PrestaShop\Adapter\Feature\Validate\FeatureValidator: ~

  PrestaShop\PrestaShop\Adapter\Feature\Validate\FeatureValueValidator: ~

  PrestaShop\PrestaShop\Adapter\Feature\Repository\FeatureValueRepository:
    autowire: true
    public: true
