services:
  _defaults:
    public: true

  prestashop.adapter.group.provider.default_groups_provider:
    class: 'PrestaShop\PrestaShop\Adapter\Group\Provider\DefaultGroupsProvider'
    arguments:
      - '@prestashop.adapter.legacy.configuration'
      - '@=service("prestashop.adapter.legacy.context").getContext().language.id'

  PrestaShop\PrestaShop\Adapter\Customer\Group\Repository\GroupRepository: ~

  prestashop.adapter.group.group_data_provider:
    class: 'PrestaShop\PrestaShop\Adapter\Group\GroupDataProvider'

  prestashop.adapter.feature.group_feature:
    class: 'PrestaShop\PrestaShop\Adapter\Feature\GroupFeature'
    arguments:
      - '@prestashop.adapter.legacy.configuration'

  PrestaShop\PrestaShop\Adapter\Customer\Group\CommandHandler\AddCustomerGroupHandler:
    public: false
    autowire: true
    autoconfigure: true

  PrestaShop\PrestaShop\Adapter\Customer\Group\QueryHandler\GetCustomerGroupForEditingHandler:
    public: false
    autowire: true
    autoconfigure: true

  PrestaShop\PrestaShop\Adapter\Customer\Group\Validate\CustomerGroupValidator:
    public: false
    autowire: true
