services:
  _defaults:
    public: true

  prestashop.adapter.hook.command_handler.update_hook_status_handler:
    class: PrestaShop\PrestaShop\Adapter\Hook\CommandHandler\UpdateHookStatusCommandHandler
    autoconfigure: true

  prestashop.adapter.hook.command_handler.get_hook_status_handler:
    class: PrestaShop\PrestaShop\Adapter\Hook\QueryHandler\GetHookStatusHandler
    autoconfigure: true

  prestashop.adapter.hook.command_handler.get_hook_handler:
    class: PrestaShop\PrestaShop\Adapter\Hook\QueryHandler\GetHookHandler
    autoconfigure: true

  PrestaShop\PrestaShop\Adapter\HookManager: ~

  prestashop.adapter.hook.manager:
    alias: PrestaShop\PrestaShop\Adapter\HookManager
