services:
  _defaults:
    public: true

  prestashop.adapter.hook.command_handler.update_hook_status_handler:
    class: PrestaShop\PrestaShop\Adapter\Hook\CommandHandler\UpdateHookStatusCommandHandler
    tags:
      - name: messenger.cqrs_handler
        command: PrestaShop\PrestaShop\Core\Domain\Hook\Command\UpdateHookStatusCommand

  prestashop.adapter.hook.command_handler.get_hook_status_handler:
    class: PrestaShop\PrestaShop\Adapter\Hook\QueryHandler\GetHookStatusHandler
    tags:
      - name: messenger.cqrs_handler
        command: PrestaShop\PrestaShop\Core\Domain\Hook\Query\GetHookStatus

  PrestaShop\PrestaShop\Adapter\HookManager: ~

  prestashop.adapter.hook.manager:
    alias: PrestaShop\PrestaShop\Adapter\HookManager
