services:
    _defaults:
        public: true

    prestashop.adapter.image.uploader.category_cover_image_uploader:
        class: 'PrestaShop\PrestaShop\Adapter\Image\Uploader\CategoryCoverImageUploader'

    prestashop.adapter.image.uploader.category_thumbnail_image_uploader:
      class: 'PrestaShop\PrestaShop\Adapter\Image\Uploader\CategoryThumbnailImageUploader'
