services:
  _defaults:
    public: true

  PrestaShop\PrestaShop\Core\Domain\Store\Repository\StoreRepository:
    autowire: true
    public: false
    arguments:
      $connection: '@doctrine.dbal.default_connection'
      $dbPrefix: '%database_prefix%'

  prestashop.adapter.store.query_handler.get_store_for_editing:
    class: 'PrestaShop\PrestaShop\Adapter\Store\QueryHandler\GetStoreForEditingHandler'
    arguments:
      - '@prestashop.core.domain.store.repository.store_repository'
    tags:
      - { name: messenger.message_handler, handles: PrestaShop\PrestaShop\Core\Domain\Store\Query\GetStoreForEditing, method: handle }

  prestashop.adapter.store.command_handler.toggle_store_status:
    class: 'PrestaShop\PrestaShop\Adapter\Store\CommandHandler\ToggleStoreStatusHandler'
    arguments:
      - '@prestashop.core.domain.store.repository.store_repository'
    tags:
      - { name: messenger.message_handler, handles: PrestaShop\PrestaShop\Core\Domain\Store\Command\ToggleStoreStatusCommand, method: handle }

  prestashop.adapter.store.command_handler.bulk_toggle_store_status_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Store\CommandHandler\BulkUpdateStoreStatusHandler'
    arguments:
      - '@prestashop.core.domain.store.repository.store_repository'
    tags:
      - { name: messenger.message_handler, handles: PrestaShop\PrestaShop\Core\Domain\Store\Command\BulkUpdateStoreStatusCommand, method: handle }

  prestashop.adapter.store.command_handler.delete_store:
    class: 'PrestaShop\PrestaShop\Adapter\Store\CommandHandler\DeleteStoreHandler'
    arguments:
      - '@prestashop.core.domain.store.repository.store_repository'
    tags:
      - { name: messenger.message_handler, handles: PrestaShop\PrestaShop\Core\Domain\Store\Command\DeleteStoreCommand, method: handle }

  prestashop.adapter.store.command_handler.bulk_delete_store_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Store\CommandHandler\BulkDeleteStoreHandler'
    arguments:
      - '@prestashop.core.domain.store.repository.store_repository'
    tags:
      - { name: messenger.message_handler, handles: PrestaShop\PrestaShop\Core\Domain\Store\Command\BulkDeleteStoreCommand, method: handle }

  # deprecated
  prestashop.core.domain.store.repository.store_repository:
    alias: PrestaShop\PrestaShop\Core\Domain\Store\Repository\StoreRepository
    deprecated: ~
