services:
  _defaults:
    public: true

# Command handlers

  prestashop.adapter.supplier.command_handler.toggle_supplier_status_handler:
    class: PrestaShop\PrestaShop\Adapter\Supplier\CommandHandler\ToggleSupplierStatusHandler
    tags:
      - name: tactician.handler
        command: PrestaShop\PrestaShop\Core\Domain\Supplier\Command\ToggleSupplierStatusCommand

