services:
  _defaults:
    public: true

  prestashop.adapter.tax.ecotax.ecotax_resetter:
    class: 'PrestaShop\PrestaShop\Adapter\Tax\Ecotax\ProductEcotaxResetter'

    # Command handlers
  prestashop.adapter.tax.command_handler.delete_tax_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Tax\CommandHandler\DeleteTaxHandler'
    tags:
      - { name: 'tactician.handler', command: 'PrestaShop\PrestaShop\Core\Domain\Tax\Command\DeleteTaxCommand' }

  prestashop.adapter.tax.command_handler.toggle_tax_status_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Tax\CommandHandler\ToggleTaxStatusHandler'
    tags:
      - { name: 'tactician.handler', command: 'PrestaShop\PrestaShop\Core\Domain\Tax\Command\ToggleTaxStatusCommand' }
      -
    prestashop.adapter.tax.command_handler.bulk_update_tax_status_handler:
      class: 'PrestaShop\PrestaShop\Adapter\Tax\CommandHandler\BulkUpdateTaxStatusHandler'
      tags:
        - { name: 'tactician.handler', command: 'PrestaShop\PrestaShop\Core\Domain\Tax\Command\BulkUpdateTaxStatusCommand' }
        -
    prestashop.adapter.tax.command_handler.bulk_delete_tax_handler:
      class: 'PrestaShop\PrestaShop\Adapter\Tax\CommandHandler\BulkDeleteTaxHandler'
      tags:
        - { name: 'tactician.handler', command: 'PrestaShop\PrestaShop\Core\Domain\Tax\Command\BulkDeleteTaxCommand' }
