services:
  _defaults:
    public: true

  prestashop.adapter.tax.ecotax.ecotax_resetter:
    class: 'PrestaShop\PrestaShop\Adapter\Tax\Ecotax\ProductEcotaxResetter'

  PrestaShop\PrestaShop\Adapter\Tax\TaxComputer:
    arguments:
      - '@PrestaShop\PrestaShop\Adapter\TaxRulesGroup\Repository\TaxRulesGroupRepository'

  prestashop.adapter.tax.tax_computer:
    alias: PrestaShop\PrestaShop\Adapter\Tax\TaxComputer
    deprecated: ~

  # Command handlers
  prestashop.adapter.tax.command_handler.delete_tax_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Tax\CommandHandler\DeleteTaxHandler'
    autoconfigure: true

  prestashop.adapter.tax.command_handler.toggle_tax_status_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Tax\CommandHandler\ToggleTaxStatusHandler'
    autoconfigure: true

  prestashop.adapter.tax.command_handler.bulk_toggle_tax_status_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Tax\CommandHandler\BulkToggleTaxStatusHandler'
    autoconfigure: true

  prestashop.adapter.tax.command_handler.bulk_delete_tax_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Tax\CommandHandler\BulkDeleteTaxHandler'
    autoconfigure: true

  prestashop.adapter.tax.query_handler.get_tax_for_editing_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Tax\QueryHandler\GetTaxForEditingHandler'
    autoconfigure: true

  prestashop.adapter.tax.command_handler.edit_tax_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Tax\CommandHandler\EditTaxHandler'
    autoconfigure: true

  prestashop.adapter.tax.command_handler.add_tax_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Tax\CommandHandler\AddTaxHandler'
    autoconfigure: true
