services:
  _defaults:
    public: true

  PrestaShop\PrestaShop\Adapter\TaxRulesGroup\CommandHandler\AddTaxRulesGroupHandler:
    autowire: true
    tags:
      - name: 'messenger.cqrs_handler'
        command: 'PrestaShop\PrestaShop\Core\Domain\TaxRulesGroup\Command\AddTaxRulesGroupCommand'

  PrestaShop\PrestaShop\Adapter\TaxRulesGroup\CommandHandler\EditTaxRulesGroupHandler:
    autowire: true
    tags:
      - name: 'messenger.cqrs_handler'
        command: 'PrestaShop\PrestaShop\Core\Domain\TaxRulesGroup\Command\EditTaxRulesGroupCommand'

  prestashop.adapter.tax_rules_group.command_handler.delete_tax_rules_group_handler:
    class: 'PrestaShop\PrestaShop\Adapter\TaxRulesGroup\CommandHandler\DeleteTaxRulesGroupHandler'
    tags:
      - name: 'messenger.cqrs_handler'
        command: 'PrestaShop\PrestaShop\Core\Domain\TaxRulesGroup\Command\DeleteTaxRulesGroupCommand'

  prestashop.adapter.tax_rules_group.command_handler.bulk_delete_tax_rules_group_handler:
    class: 'PrestaShop\PrestaShop\Adapter\TaxRulesGroup\CommandHandler\BulkDeleteTaxRulesGroupHandler'
    tags:
      - name: 'messenger.cqrs_handler'
        command: 'PrestaShop\PrestaShop\Core\Domain\TaxRulesGroup\Command\BulkDeleteTaxRulesGroupCommand'

  prestashop.adapter.tax_rules_group.command_handler.bulk_set_tax_rules_group_status_handler:
    class: 'PrestaShop\PrestaShop\Adapter\TaxRulesGroup\CommandHandler\BulkSetTaxRulesGroupStatusHandler'
    tags:
      - name: 'messenger.cqrs_handler'
        command: 'PrestaShop\PrestaShop\Core\Domain\TaxRulesGroup\Command\BulkSetTaxRulesGroupStatusCommand'

  prestashop.adapter.tax_rules_group.query_handler.get_tax_rules_group_for_editing:
    class: 'PrestaShop\PrestaShop\Adapter\TaxRulesGroup\QueryHandler\GetTaxRulesGroupForEditingHandler'
    tags:
      - name: 'messenger.cqrs_handler'
        command: 'PrestaShop\PrestaShop\Core\Domain\TaxRulesGroup\Query\GetTaxRulesGroupForEditing'

  prestashop.adapter.tax_rules_group.command_handler.set_tax_rules_group_status_handler:
    class: 'PrestaShop\PrestaShop\Adapter\TaxRulesGroup\CommandHandler\SetTaxRulesGroupStatusHandler'
    tags:
      - name: 'messenger.cqrs_handler'
        command: 'PrestaShop\PrestaShop\Core\Domain\TaxRulesGroup\Command\SetTaxRulesGroupStatusCommand'

  PrestaShop\PrestaShop\Adapter\TaxRulesGroup\Repository\TaxRulesGroupRepository:
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'
      - '@PrestaShop\PrestaShop\Adapter\TaxRulesGroup\Validate\TaxRulesGroupValidator'

  PrestaShop\PrestaShop\Adapter\TaxRulesGroup\Validate\TaxRulesGroupValidator: ~

  prestashop.adapter.tax_rules_group.repository.tax_rules_group_repository:
    alias: PrestaShop\PrestaShop\Adapter\TaxRulesGroup\Repository\TaxRulesGroupRepository
    deprecated: ~
