services:
  _defaults:
    public: true

  prestashop.adapter.theme.command_handler.import_theme_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Theme\CommandHandler\ImportThemeHandler'
    arguments:
      - '@prestashop.core.addon.theme.theme_zip_uploader'
      - '@prestashop.core.addon.theme.theme_manager'
      - '@prestashop.adapter.legacy.configuration'
    tags:
      - { name: tactician.handler, command: PrestaShop\PrestaShop\Core\Domain\Theme\Command\ImportThemeCommand }

  prestashop.adapter.theme.command_handler.enable_theme_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Theme\CommandHandler\EnableThemeHandler'
    arguments:
      - '@prestashop.core.addon.theme.theme_manager'
      - '@prestashop.adapter.cache.clearer.smarty_cache_clearer'
    tags:
      - { name: tactician.handler, command: PrestaShop\PrestaShop\Core\Domain\Theme\Command\EnableThemeCommand }
