services:
  _defaults:
    public: true

  PrestaShop\PrestaShop\Adapter\Title\CommandHandler\AddTitleHandler:
    autowire: true
    tags:
      - name: 'messenger.cqrs_handler'
        command: 'PrestaShop\PrestaShop\Core\Domain\Title\Command\AddTitleCommand'

  PrestaShop\PrestaShop\Adapter\Title\CommandHandler\EditTitleHandler:
    autowire: true
    tags:
      - name: 'messenger.cqrs_handler'
        command: 'PrestaShop\PrestaShop\Core\Domain\Title\Command\EditTitleCommand'

  prestashop.adapter.title.title_image_thumbnail_provider:
    class: 'PrestaShop\PrestaShop\Adapter\Title\TitleImageThumbnailProvider'
    arguments:
      - '@prestashop.core.image.parser.image_tag_source_parser'
      - '@PrestaShop\PrestaShop\Adapter\ImageManager'
      - !php/const _PS_GENDERS_DIR_

  prestashop.adapter.title.command_handler.delete_title_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Title\CommandHandler\DeleteTitleHandler'
    autowire: true
    tags:
      - name: messenger.cqrs_handler
        command: 'PrestaShop\PrestaShop\Core\Domain\Title\Command\DeleteTitleCommand'

  prestashop.adapter.title.command_handler.bulk_delete_title_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Title\CommandHandler\BulkDeleteTitleHandler'
    autowire: true
    tags:
      - name: messenger.cqrs_handler
        command: 'PrestaShop\PrestaShop\Core\Domain\Title\Command\BulkDeleteTitleCommand'

  PrestaShop\PrestaShop\Adapter\Title\QueryHandler\GetTitleForEditingHandler:
    autowire: true
    tags:
      - name: messenger.cqrs_handler
        command: 'PrestaShop\PrestaShop\Core\Domain\Title\Query\GetTitleForEditing'

  PrestaShop\PrestaShop\Adapter\Title\Repository\TitleRepository:
    autowire: true

  PrestaShop\PrestaShop\Adapter\Title\Validate\TitleValidator: ~
