services:
    _defaults:
        public: true

    prestashop.adapter.webservice.webservice_key_eraser:
      class: 'PrestaShop\PrestaShop\Adapter\Webservice\WebserviceKeyEraser'

    prestashop.adapter.webservice.webservice_key_status_modifier:
      class: 'PrestaShop\PrestaShop\Adapter\Webservice\WebserviceKeyStatusModifier'
      arguments:
          - '@translator'

    prestashop.adapter.webservice.query_handler.get_webservice_key_for_editing_handler:
      class: 'PrestaShop\PrestaShop\Adapter\Webservice\QueryHandler\GetWebserviceKeyForEditingHandler'
      tags:
        - name: tactician.handler
          command: 'PrestaShop\PrestaShop\Core\Domain\Webservice\Query\GetWebserviceKeyForEditing'
