services:
    _defaults:
        public: true

    prestashop.adapter.pdf.type_provider.invoice:
        class: PrestaShop\PrestaShop\Adapter\Invoice\InvoiceTemplateTypeProvider

    prestashop.adapter.pdf.type_provider.credit_slip:
        class: PrestaShop\PrestaShop\Adapter\CreditSlip\CreditSlipTemplateTypeProvider
