services:
    _defaults:
        public: true

    prestashop.core.grid.definition.factory.abstract_grid_definition:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\AbstractGridDefinitionFactory'
        abstract: true
        arguments:
            - '@prestashop.core.hook.dispatcher'
        calls:
            - [setTranslator, ['@translator']]

    prestashop.core.grid.definition.factory.logs:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\LogGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        public: true

    prestashop.core.grid.definition.factory.email_logs:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\EmailLogsDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        arguments:
            - "@=service('router').generate('admin_common_reset_search', {'controller': 'email', 'action': 'index'})"
            - "@=service('router').generate('admin_emails_index')"
            - '@prestashop.core.form.choice_provider.language_by_id'
        public: true

    prestashop.core.grid.definition.factory.request_sql:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\RequestSqlGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        public: true

    prestashop.core.grid.definition.factory.backup:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\BackupDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        public: true

    prestashop.core.grid.definition.factory.webservice_key:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\WebserviceKeyDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        arguments:
            - '@=service("prestashop.core.form.choice_provider.status").getChoices()'
        public: true

    prestashop.core.grid.definition.factory.meta:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\MetaGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        public: true

    prestashop.core.grid.definition.factory.category:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\CategoryGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        arguments:
            - "@=service('router').generate('admin_common_reset_search', {'controller': 'category', 'action': 'index'})"
            - "@=service('router').generate('admin_categories_index')"
            - '@prestashop.adapter.shop.context'
            - '@prestashop.adapter.grid.action.row.accessibility_checker.category_for_view'
        public: true

    prestashop.core.grid.definition.factory.employee:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\EmployeeGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        arguments:
            - "@=service('router').generate('admin_common_reset_search', {'controller': 'employee', 'action': 'index'})"
            - "@=service('router').generate('admin_employees_index')"
        public: true

    prestashop.core.grid.definition.factory.contacts:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\ContactGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        arguments:
            - "@=service('router').generate('admin_common_reset_search', {'controller': 'contacts', 'action': 'index'})"
            - "@=service('router').generate('admin_contacts_index')"
        public: true

    prestashop.core.grid.definition.factory.customer:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\CustomerGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        arguments:
            - '@=service("prestashop.core.b2b.b2b_feature").isActive()'
            - '@=service("prestashop.adapter.multistore_feature").isActive()'
            - '@=service("prestashop.adapter.form.choice_provider.gender_by_id_choice_provider").getChoices()'
        public: true

    prestashop.core.grid.definition.factory.customer.discount:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\CustomerDiscountGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        public: true

    prestashop.core.grid.definition.factory.customer.address:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\CustomerAddressGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        arguments:
            - '@=service("request_stack").getCurrentRequest()'
        public: true

    prestashop.core.grid.definition.factory.language:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\LanguageGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        public: true

    prestashop.core.grid.definition.factory.currency:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\CurrencyGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        public: true

    prestashop.core.grid.definition.factory.supplier:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\SupplierGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        public: true

    prestashop.core.grid.definition.factory.profile:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\ProfileGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        arguments:
            - "@=service('router').generate('admin_common_reset_search', {'controller': 'profile', 'action': 'index'})"
            - "@=service('router').generate('admin_profiles_index')"
            - '@prestashop.core.grid.action.row.accessibility_checker.delete_profile'
        public: true

    prestashop.core.grid.definition.factory.cms_page_category:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\CmsPageCategoryDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        arguments:
            - '@request_stack'
            - '@prestashop.adapter.shop.context'
            - '@=service("prestashop.adapter.multistore_feature").isUsed()'
        public: true

    prestashop.core.grid.definition.factory.tax:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\TaxGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        public: true

    prestashop.core.grid.definition.factory.manufacturer:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\ManufacturerGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        public: true

    prestashop.core.grid.definition.factory.manufacturer_address:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\ManufacturerAddressGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        public: true

    prestashop.core.grid.definition.factory.cms_page:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\CmsPageDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        arguments:
            - '@prestashop.core.query_bus'
            - '@request_stack'
            - '@prestashop.adapter.shop.context'
            - '@=service("prestashop.adapter.multistore_feature").isUsed()'
        public: true

    prestashop.core.grid.definition.factory.monitoring.empty_category:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\Monitoring\EmptyCategoryGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        arguments:
            - '@prestashop.adapter.grid.action.row.accessibility_checker.category_for_view'
        public: true

    prestashop.core.grid.definition.factory.monitoring.no_qty_product_with_combination:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\Monitoring\NoQtyProductWithCombinationGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        public: true

    prestashop.core.grid.definition.factory.monitoring.no_qty_product_without_combination:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\Monitoring\NoQtyProductWithoutCombinationGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        public: true

    prestashop.core.grid.definition.factory.monitoring.disabled_product:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\Monitoring\DisabledProductGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        public: true

    prestashop.core.grid.definition.factory.monitoring.product_without_image:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\Monitoring\ProductWithoutImageGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        public: true

    prestashop.core.grid.definition.factory.monitoring.product_without_description:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\Monitoring\ProductWithoutDescriptionGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        public: true

    prestashop.core.grid.definition.factory.monitoring.product_without_price:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\Monitoring\ProductWithoutPriceGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        public: true

    prestashop.core.grid.definition.factory.order:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\OrderGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        arguments:
            - '@prestashop.adapter.legacy.configuration'
            - '@prestashop.adapter.form.choice_provider.order_countries'
            - '@prestashop.core.form.choice_provider.order_state_by_id'
            - '@=service("prestashop.adapter.legacy.context").getContext().language.date_format_full'
            - '@prestashop.adapter.feature.multistore'
            - '@prestashop.core.grid.action.row.accessibility_checker.print_invoice'
            - '@prestashop.core.grid.action.row.accessibility_checker.print_delivery_slip'
            - '@prestashop.core.form.choice_provider.order_state_by_id'
        public: true

    prestashop.core.grid.definition.factory.cart_rule:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\CartRuleGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        public: true
        arguments:
          - '@=service("prestashop.adapter.legacy.context").getContext().language.date_format_full'

    prestashop.core.grid.definition.factory.catalog_price_rule:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\CatalogPriceRuleGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        arguments:
            - '@request_stack'
            - '@prestashop.adapter.shop.context'
            - '@=service("prestashop.adapter.multistore_feature").isUsed()'
        public: true

    prestashop.core.grid.definition.factory.order_message:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\OrderMessageGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        public: true

    prestashop.core.grid.definition.factory.attachment:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\AttachmentGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        public: true

    prestashop.core.grid.definition.factory.attribute:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\AttributeGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        arguments:
            - '@=service("request_stack").getCurrentRequest().attributes.getInt("attributeGroupId")'
            - '@prestashop.adapter.product.attribute_group.attribute_group_view_data_provider'
        public: true

    prestashop.core.grid.definition.factory.attribute_group:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\AttributeGroupGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        public: true

    prestashop.core.grid.definition.factory.merchandise_return:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\MerchandiseReturnGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        public: true

    prestashop.core.grid.definition.factory.tax_rules_group:
      class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\TaxRulesGroupGridDefinitionFactory'
      parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
      public: true

    prestashop.core.grid.definition.factory.address:
      class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\AddressGridDefinitionFactory'
      parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
      public: true

    prestashop.core.grid.definition.factory.credit_slip:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\CreditSlipGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        arguments:
            - '@=service("prestashop.adapter.legacy.context").getLanguage().date_format_lite'
        public: true

    prestashop.core.grid.definition.factory.order_states:
      class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\OrderStatesGridDefinitionFactory'
      parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
      public: true

    prestashop.core.grid.definition.factory.order_return_states:
      class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\OrderReturnStatesGridDefinitionFactory'
      parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
      public: true

    prestashop.core.grid.definition.factory.outstanding:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\OutstandingGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        arguments:
            - '@prestashop.adapter.legacy.configuration'
            - "@=service('prestashop.adapter.legacy.context').getContext().language.id"
        public: true

    prestashop.core.grid.definition.factory.carrier:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\CarrierGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        public: true

    prestashop.core.grid.definition.factory.zone:
      class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\ZoneGridDefinitionFactory'
      parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
      public: true
