services:
    _defaults:
        public: true

    prestashop.core.grid.log_factory:
        class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
        arguments:
            - '@prestashop.core.grid.definition.factory.logs'
            - '@prestashop.core.grid.data_factory.log'
            - '@prestashop.core.grid.filter.form_factory'
            - '@prestashop.core.hook.dispatcher'

    prestashop.core.grid.factory.email_logs:
        class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
        arguments:
            - '@prestashop.core.grid.definition.factory.email_logs'
            - '@prestashop.core.grid.data_factory.email_logs'
            - '@prestashop.core.grid.filter.form_factory'
            - '@prestashop.core.hook.dispatcher'

    prestashop.core.grid.factory.request_sql:
        class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
        arguments:
            - '@prestashop.core.grid.definition.factory.request_sql'
            - '@prestashop.core.grid.data_factory.request_sql'
            - '@prestashop.core.grid.filter.form_factory'
            - '@prestashop.core.hook.dispatcher'

    prestashop.core.grid.factory.backup:
        class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
        arguments:
            - '@prestashop.core.grid.definition.factory.backup'
            - '@prestashop.core.backup.listing.grid_data_factory'
            - '@prestashop.core.grid.filter.form_factory'
            - '@prestashop.core.hook.dispatcher'

    prestashop.core.grid.factory.webservice_key:
        class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
        arguments:
            - '@prestashop.core.grid.definition.factory.webservice_key'
            - '@prestashop.core.grid.data_factory.webservice_key'
            - '@prestashop.core.grid.filter.form_factory'
            - '@prestashop.core.hook.dispatcher'

    prestashop.core.grid.factory.meta:
        class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
        arguments:
            - '@prestashop.core.grid.definition.factory.meta'
            - '@prestashop.core.grid.data_provider.meta'
            - '@prestashop.core.grid.filter.form_factory'
            - '@prestashop.core.hook.dispatcher'

    prestashop.core.grid.factory.category:
        class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
        arguments:
            - '@prestashop.core.grid.definition.factory.category'
            - '@prestashop.core.grid.data.factory.category_decorator'
            - '@prestashop.core.grid.filter.category_form_factory'
            - '@prestashop.core.hook.dispatcher'

    prestashop.core.grid.factory.category_decorator:
        class: 'PrestaShop\PrestaShop\Core\Grid\Factory\CategoryGridFactoryDecorator'
        arguments:
          - '@prestashop.core.grid.factory.category'

    prestashop.core.grid.factory.employee:
        class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
        arguments:
            - '@prestashop.core.grid.definition.factory.employee'
            - '@prestashop.core.grid.data_provider.employee'
            - '@prestashop.core.grid.filter.form_factory'
            - '@prestashop.core.hook.dispatcher'

    prestashop.core.grid.factory.contacts:
        class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
        arguments:
            - '@prestashop.core.grid.definition.factory.contacts'
            - '@prestashop.core.grid.data_provider.contacts'
            - '@prestashop.core.grid.filter.form_factory'
            - '@prestashop.core.hook.dispatcher'

    prestashop.core.grid.factory.customer:
        class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
        arguments:
            - '@prestashop.core.grid.definition.factory.customer'
            - '@prestashop.core.grid.data_provider.customer_decorator'
            - '@prestashop.core.grid.filter.form_factory'
            - '@prestashop.core.hook.dispatcher'

    prestashop.core.grid.factory.language:
        class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
        arguments:
            - '@prestashop.core.grid.definition.factory.language'
            - '@prestashop.core.grid.factory.language_decorator'
            - '@prestashop.core.grid.filter.form_factory'
            - '@prestashop.core.hook.dispatcher'

    prestashop.core.grid.factory.supplier:
        class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
        arguments:
            - '@prestashop.core.grid.definition.factory.supplier'
            - '@prestashop.core.grid.factory.supplier_decorator'
            - '@prestashop.core.grid.filter.form_factory'
            - '@prestashop.core.hook.dispatcher'

    prestashop.core.grid.factory.currency:
        class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
        arguments:
            - '@prestashop.core.grid.definition.factory.currency'
            - '@prestashop.core.currency.grid_data_factory'
            - '@prestashop.core.grid.filter.form_factory'
            - '@prestashop.core.hook.dispatcher'

    prestashop.core.grid.factory.profiles:
        class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
        arguments:
            - '@prestashop.core.grid.definition.factory.profile'
            - '@prestashop.core.grid.data_factory.profiles'
            - '@prestashop.core.grid.filter.form_factory'
            - '@prestashop.core.hook.dispatcher'

    prestashop.core.grid.factory.cms_page_category:
        class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
        arguments:
            - '@prestashop.core.grid.definition.factory.cms_page_category'
            - '@prestashop.core.grid.data_provider.cms_page_category'
            - '@prestashop.core.grid.filter.cms_page_form_factory'
            - '@prestashop.core.hook.dispatcher'

    prestashop.core.grid.factory.tax:
        class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
        arguments:
            - '@prestashop.core.grid.definition.factory.tax'
            - '@prestashop.core.grid.data_factory.tax'
            - '@prestashop.core.grid.filter.form_factory'
            - '@prestashop.core.hook.dispatcher'

    prestashop.core.grid.grid_factory.manufacturer:
        class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
        arguments:
            - '@prestashop.core.grid.definition.factory.manufacturer'
            - '@prestashop.core.grid.data.factory.manufacturer_decorator'
            - '@prestashop.core.grid.filter.form_factory'
            - '@prestashop.core.hook.dispatcher'

    prestashop.core.grid.grid_factory.manufacturer_address:
        class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
        arguments:
            - '@prestashop.core.grid.definition.factory.manufacturer_address'
            - '@prestashop.core.grid.data.factory.manufacturer_address_decorator'
            - '@prestashop.core.grid.filter.form_factory'
            - '@prestashop.core.hook.dispatcher'

    prestashop.core.grid.factory.cms_page:
        class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
        arguments:
            - '@prestashop.core.grid.definition.factory.cms_page'
            - '@prestashop.core.grid.data_provider.cms_page'
            - '@prestashop.core.grid.filter.cms_page_form_factory'
            - '@prestashop.core.hook.dispatcher'
