services:
    _defaults:
        public: true

    prestashop.core.grid.definition.factory.abstract_grid_definition:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\AbstractGridDefinitionFactory'
        abstract: true
        calls:
            - [setTranslator, ['@translator']]
            - [setHookDispatcher, ['@prestashop.core.hook.dispatcher']]

    prestashop.core.grid.definition.factory.logs:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\LogGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        arguments:
            - "@=service('router').generate('admin_common_reset_search', {'controller': 'logs', 'action': 'index'})"
            - "@=service('router').generate('admin_logs_index')"
        public: true

    prestashop.core.grid.definition.factory.email_logs:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\EmailLogsDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        arguments:
            - "@=service('router').generate('admin_common_reset_search', {'controller': 'email', 'action': 'index'})"
            - "@=service('router').generate('admin_emails_index')"
            - '@prestashop.core.form.choice_provider.language_by_id'
        public: true

    prestashop.core.grid.definition.factory.request_sql:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\RequestSqlGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        arguments:
            - "@=service('router').generate('admin_common_reset_search', {'controller': 'sqlmanager', 'action': 'index'})"
            - "@=service('router').generate('admin_sql_requests_index')"
        public: true

    prestashop.core.grid.definition.factory.backup:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\BackupDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        public: true

    prestashop.core.grid.definition.factory.webservice_key:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\WebserviceKeyDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        arguments:
            - '@=service("prestashop.core.form.choice_provider.status").getChoices()'
            - "@=service('router').generate('admin_common_reset_search', {'controller': 'webservice', 'action': 'index'})"
            - "@=service('router').generate('admin_webservice_keys_index')"
        public: true

    prestashop.core.grid.definition.factory.meta:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\MetaGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        arguments:
            - "@=service('router').generate('admin_common_reset_search', {'controller': 'meta', 'action': 'index'})"
            - "@=service('router').generate('admin_metas_index')"
        public: true

    prestashop.core.grid.definition.factory.category:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\CategoryGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        arguments:
            - "@=service('router').generate('admin_common_reset_search', {'controller': 'category', 'action': 'index'})"
            - "@=service('router').generate('admin_category_listing')"
            - '@prestashop.adapter.shop.context'
            - '@prestashop.adapter.grid.action.row.accessibility_checker.category_for_view'
        public: true

    prestashop.core.grid.definition.factory.employee:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\EmployeeGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        arguments:
            - "@=service('router').generate('admin_common_reset_search', {'controller': 'employee', 'action': 'index'})"
            - "@=service('router').generate('admin_employees_index')"
        public: true

    prestashop.core.grid.definition.factory.contacts:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\ContactGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        arguments:
            - "@=service('router').generate('admin_common_reset_search', {'controller': 'contacts', 'action': 'index'})"
            - "@=service('router').generate('admin_contacts_index')"
        public: true

    prestashop.core.grid.definition.factory.customer:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\CustomerGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        arguments:
            - '@=service("prestashop.core.b2b.b2b_feature").isActive()'
            - '@=service("prestashop.adapter.multistore_feature").isActive()'
            - '@=service("prestashop.adapter.form.choice_provider.gender_by_id_choice_provider").getChoices()'
        public: true

    prestashop.core.grid.definition.factory.language:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\LanguageGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        arguments:
            - "@=service('router').generate('admin_common_reset_search', {'controller': 'language', 'action': 'index'})"
            - "@=service('router').generate('admin_languages_index')"
        public: true

    prestashop.core.grid.definition.factory.currency:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\CurrencyGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        public: true

    prestashop.core.grid.definition.factory.supplier:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\SupplierGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        public: true

    prestashop.core.grid.definition.factory.profiles:
        class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\ProfilesGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        arguments:
            - "@=service('router').generate('admin_common_reset_search', {'controller': 'profiles', 'action': 'index'})"
            - "@=service('router').generate('admin_profiles_index')"
            - '@prestashop.core.grid.action.row.accessibility_checker.delete_profile'
        public: true

    prestashop.core.grid.definition.factory.manufacturer_grid_definition_factory:
      class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\ManufacturerGridDefinitionFactory'
      parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
      public: true

    prestashop.core.grid.definition.factory.manufacturer_address_grid_definition_factory:
      class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\ManufacturerAddressGridDefinitionFactory'
      parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
      arguments:
        - "@=service('router').generate('admin_common_reset_search', {'controller': 'manufacturer', 'action': 'index'})"
        - "@=service('router').generate('admin_manufacturers_index')"
      public: true
