# For UI tests as job is required
name: Behaviour tests
on:
  push:
  pull_request:
    # Run when only tests are updated
    paths:
      - 'tests/UI/**'

concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  behaviour:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No tests required"'
