# This workflow aim to run all UI tests on active branches
# and upload the report on Google cloud platform storage
name: Nightly tests and report - 1.7.8.x

on:
  workflow_run:
    workflows: [ 'Nightly Build' ]
    types:
      - requested

jobs:
  test_1_7_8_x:
    uses: ./.github/workflows/cron_nightly_tests_reusable.yml
    with:
      BRANCH: 1.7.8.x
      PHP_VERSION: '7.4'
    secrets:
      GC_PROJECT_ID: ${{ secrets.GC_PROJECT_ID }}
      GC_SERVICE_KEY: ${{ secrets.GC_SERVICE_KEY }}
      API_NIGHTLY_IMPORT_TOKEN: ${{ secrets.NIGHTLY_TOKEN }}
