name: Js
on:
  push:
  pull_request:

permissions:
  contents: read
concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  js-unit-tests:
    runs-on: ubuntu-latest
    name: Run unit tests
    strategy:
      matrix:
        js: [ '16' ]
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.js }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Node Directory
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Run tests
        run: npm ci && npm run test
        working-directory: ./admin-dev/themes/new-theme
