name: UI tests code checks

on:
  pull_request:
      types: [opened,edited,reopened,synchronize,labeled]

defaults:
  run:
      working-directory: ./tests/UI/

jobs:

  ESLint:
    runs-on: ubuntu-latest
    name: ESLint
    if: contains(github.event.pull_request.labels.*.name, 'TE')

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: |
            admin-dev/**/package-lock.json
            tests/**/package-lock.json
            themes/**/package-lock.json

      - name: Setup NPM
        shell: bash
        run: npm i -g npm@6

      - name: Cache Playwright browsers
        uses: actions/cache@v2
        with:
          path: ~/.cache/ms-playwright/
          key: ${{ runner.os }}-browsers

      - name: Install dependencies in UI tests directory
        run: npm install

      - name: Check eslint errors
        run: npm run lint

  Steps-identifiers:
    runs-on: ubuntu-latest
    name: Checking doubles in steps identifiers
    if: contains(github.event.pull_request.labels.*.name, 'TE')

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: |
            admin-dev/**/package-lock.json
            tests/**/package-lock.json
            themes/**/package-lock.json

      - name: Setup NPM
        shell: bash
        run: npm i -g npm@6

      - name: Cache Playwright browsers
        uses: actions/cache@v2
        with:
          path: ~/.cache/ms-playwright/
          key: ${{ runner.os }}-browsers

      - name: Install dependencies in UI tests directory
        run: npm install

      - name: Generate mocha reports with failed steps
        run: GENERATE_FAILED_STEPS=true npm run test:all
        continue-on-error: true

      - name: Checking doubles in steps identifiers
        run: npm run check:step-identifiers

