name: UI tests

on:
  pull_request:
      types: [opened,edited,reopened,synchronize,labeled]

defaults:
  run:
      working-directory: ./tests/UI/

jobs:

  linter:
    runs-on: ubuntu-latest
    name: Linter
    if: contains(github.event.pull_request.labels.*.name, 'TE')

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install dependencies in UI tests directory
        run: npm install

      - name: Check eslint errors
        run: npm run lint-no-fix

  Steps-identifiers:
    runs-on: ubuntu-latest
    name: Checking doubles in steps identifiers
    if: contains(github.event.pull_request.labels.*.name, 'TE')

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install dependencies in UI tests directory
        run: npm install

      - name: Checking doubles in steps identifiers
        run: GENERATE_FAILED_STEPS=true npm run functional-tests

      - name: Checking doubles in steps identifiers
        - run: GENERATE_FAILED_STEPS=true npm run functional-tests
        if: ${{ failure() || success() }}
        - run: npm run step-idenfiers-checker
