# @todo uncomment links once page is completed
admin_merchandise_returns_index:
  path: /
  methods: [ GET ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\CustomerService\MerchandiseReturnController::indexAction
    _legacy_controller: AdminReturn
    _legacy_link: AdminReturn
    _legacy_feature_flag: order_return

admin_merchandise_returns_save_options:
  path: /options
  methods: [ PATCH, POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\CustomerService\MerchandiseReturnController::indexAction
    _legacy_controller: AdminReturn
    _legacy_link: AdminReturn:submitOptionsorder_return
    _legacy_feature_flag: order_return

admin_merchandise_returns_filter:
  path: /
  methods: [ POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\CommonController::searchGridAction
    gridDefinitionFactoryServiceId: prestashop.core.grid.definition.factory.merchandise_return
    redirectRoute: admin_merchandise_returns_index
    _legacy_controller: AdminReturn
    _legacy_link: AdminReturn:submitFilterorder_return
    _legacy_feature_flag: order_return

admin_order_returns_edit:
  path: /{orderReturnId}/edit
  methods: [ GET, POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\CustomerService\MerchandiseReturnController::editAction
    _legacy_controller: AdminReturn
    _legacy_link: AdminReturn:updateorder_return
    _legacy_feature_flag: order_return
    _legacy_parameters:
      id_order_return: orderReturnId
  requirements:
    orderReturnId: \d+

admin_order_returns_update:
  path: /{orderReturnId}/update
  methods: [ POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\CustomerService\MerchandiseReturn::editAction
    _legacy_controller: AdminReturn
    _legacy_link: AdminReturn:updateorder_return
    _legacy_feature_flag: order_return
    _legacy_parameters:
      id_order_return: orderReturnId
  requirements:
    orderReturnId: \d+

admin_order_returns_products_filter:
  path: /{orderReturnId}/edit
  methods: [POST]
  defaults:
    _controller: PrestaShopBundle:Admin\Common:searchGrid
    gridDefinitionFactoryServiceId: prestashop.core.grid.definition.factory.order_return_products
    redirectRoute: admin_order_returns_edit
    redirectQueryParamsToKeep:
      - 'orderReturnId'
    _legacy_controller: AdminReturn
    _legacy_link: AdminReturn:submitFilterorder_return
    _legacy_feature_flag: order_return
  requirements:
    orderReturnId: \d+

admin_order_returns_delete_product:
  path: /{orderReturnId}/products/{orderReturnDetailId}/delete
  methods: [POST]
  defaults:
    _controller: PrestaShopBundle:Admin/Sell/CustomerService/MerchandiseReturn:deleteProduct
    _legacy_controller: AdminReturn
    _legacy_link: AdminReturn:deleteorder_return_detail
    _legacy_feature_flag: order_return
    _legacy_parameters:
      id_order_return: orderReturnId
      id_order_detail: orderReturnDetailId
  requirements:
    orderReturnId: \d+
    orderReturnDetailId: \d+

admin_order_returns_delete_product_bulk:
  path: /{orderReturnId}/products/bulk-delete
  methods: [POST]
  defaults:
    _controller: PrestaShopBundle:Admin/Sell/CustomerService/MerchandiseReturn:bulkDeleteProduct
  requirements:
    orderReturnId: \d+

admin_order_returns_generate_pdf:
  path: /{orderReturnId}/generate-order-return-pdf
  methods: [GET]
  defaults:
    _controller: PrestaShopBundle:Admin/Sell/CustomerService/MerchandiseReturn:generateOrderReturnPdf
    _legacy_controller: AdminReturn
    _legacy_feature_flag: order_return
  requirements:
    orderReturnId: \d+
