admin_merchandise_returns_index:
  path: /
  methods: [GET]
  defaults:
    _controller: PrestaShopBundle:Admin/Sell/CustomerService/MerchandiseReturn:index
    _legacy_controller: AdminReturn
#    _legacy_link: AdminReturn

admin_merchandise_returns_save_options:
  path: /options
  methods: [POST]
  defaults:
    _controller: PrestaShopBundle:Admin/Sell/CustomerService/MerchandiseReturn:index
    _legacy_controller: AdminReturn
#    _legacy_link: AdminReturn:submitOptionsorder_return

admin_merchandise_returns_filter:
  path: /
  methods: [POST]
  defaults:
    _controller: PrestaShopBundle:Admin\Common:searchGrid
    gridDefinitionFactoryServiceId: prestashop.core.grid.definition.factory.merchandise_return
    redirectRoute: admin_merchandise_returns_index
    _legacy_controller: AdminReturn
#    _legacy_link: AdminReturn:submitFilterorder_return

admin_merchandise_returns_edit:
  path: /{merchandiseReturnId}/edit
  methods: [GET, POST]
  defaults:
    _controller: PrestaShopBundle:Admin/Sell/CustomerService/MerchandiseReturn:edit
    _legacy_controller: AdminReturn
#    _legacy_link: AdminReturn:updateorder_return
#    _legacy_parameters:
#      id_order_return: merchandiseReturnId
  requirements:
    merchandiseReturnId: \d+
