admin_order_messages_index:
  path: /
  methods: [GET, POST]
  defaults:
    _controller: PrestaShopBundle:Admin/Sell/CustomerService/OrderMessage:index

admin_order_messages_create:
  path: /new
  methods: [GET, POST]
  defaults:
    _controller: PrestaShopBundle:Admin/Sell/CustomerService/OrderMessage:create

admin_order_messages_edit:
  path: /{orderMessageId}/edit
  methods: [GET, POST]
  defaults:
    _controller: PrestaShopBundle:Admin/Sell/CustomerService/OrderMessage:edit
  requirements:
    orderMessageId: \d+

admin_order_messages_delete:
  path: /{orderMessageId}/delete
  methods: [POST]
  defaults:
    _controller: PrestaShopBundle:Admin/Sell/CustomerService/OrderMessage:delete
  requirements:
    orderMessageId: \d+

admin_order_messages_bulk_delete:
  path: /bulk-delete
  methods: [POST]
  defaults:
    _controller: PrestaShopBundle:Admin/Sell/CustomerService/OrderMessage:bulkDelete
